// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;PtysRawClient&apos; collection client.
/// </summary>
internal sealed class PtysRawClient
{
    private static readonly PtyCreateRequest EmptyPtyCreateRequest = new();
    private readonly Pipeline? _pipeline;
    internal PtysRawClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Gets a bound &apos;PtyRawClient&apos;; the handle never caches server state.
    /// </summary>
    /// <param name = "ptyId">The &apos;ptyID&apos; route value.</param>
    /// <returns>The bound &apos;PtyRawClient&apos;.</returns>
    internal PtyRawClient GetPtyRawClient(string ptyId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(ptyId);
        if (ptyId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(ptyId));
        }

        return new PtyRawClient(Pipeline, ptyId);
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("PtysRawClient", "Pipeline");

    /// <summary>
    /// Create PTY session. Create a pseudo-terminal session for a location.
    /// </summary>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PtyCreateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>pty.create</c>: <c>POST /api/pty</c>.
    /// </remarks>
    internal Task<PtyCreateResponse> CreatePtyAsync(PtyCreateRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Ptys.CreatePty(request), request ?? EmptyPtyCreateRequest, OpenCodeJsonContext.Default.PtyCreateRequest, PtyCreateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List PTY sessions. List PTY sessions for a location, including exited sessions retained until removal.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PtyListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>pty.list</c>: <c>GET /api/pty</c>.
    /// </remarks>
    internal Task<PtyListResponse> ListPtysAsync(PtyListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Ptys.ListPtys(request), PtyListResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
