// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// A bound &apos;ShellClient&apos; handle; it holds an immutable identifier and the shared pipeline.
/// </summary>
public class ShellClient
{
    private readonly Pipeline? _pipeline;
    private readonly string? _id;
    internal ShellClient(Pipeline pipeline, string id)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        ArgumentException.ThrowIfNullOrWhiteSpace(id);
        if (id is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(id));
        }

        _pipeline = pipeline;
        _id = id;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected ShellClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("ShellClient", "Pipeline");
    private string Id => _id ?? throw MockSeam.CreateError("ShellClient", "Id");

    /// <summary>
    /// Get shell command. Get one shell command, including its status and exit code once exited.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ShellResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>shell.get</c>: <c>GET /api/shell/{id}</c>.
    /// </remarks>
    public virtual Task<ShellResponse> GetAsync(ShellRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Shells.Get(Id, request), ShellResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Read shell output. Page through captured combined output by absolute byte cursor.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ShellOutputResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>shell.output</c>: <c>GET /api/shell/{id}/output</c>.
    /// </remarks>
    public virtual Task<ShellOutputResponse> GetOutputAsync(ShellOutputRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Shells.GetOutput(Id, request), ShellOutputResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Remove shell command. Terminate and remove one shell command and its retained output.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ShellRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>shell.remove</c>: <c>DELETE /api/shell/{id}</c>.
    /// </remarks>
    public virtual Task<ShellRemoveResponse> RemoveAsync(ShellRemoveRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Shells.Remove(Id, request), ShellRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
