// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;ReferencesClient&apos; collection client.
/// </summary>
public class ReferencesClient
{
    private readonly Pipeline? _pipeline;
    internal ReferencesClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected ReferencesClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("ReferencesClient", "Pipeline");

    /// <summary>
    /// List references. List references available in the requested location.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ReferenceListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>reference.list</c>: <c>GET /api/reference</c>.
    /// </remarks>
    public virtual Task<ReferenceListResponse> ListReferencesAsync(ReferenceListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.References.ListReferences(request), ReferenceListResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
