// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;ProjectsClient&apos; collection client.
/// </summary>
public class ProjectsClient
{
    private static readonly ProjectUpdateRequest EmptyProjectUpdateRequest = new();
    private readonly Pipeline? _pipeline;
    internal ProjectsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected ProjectsClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("ProjectsClient", "Pipeline");

    /// <summary>
    /// List projects. List known projects.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ProjectListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>project.list</c>: <c>GET /api/project</c>.
    /// </remarks>
    public virtual Task<ProjectListResponse> ListProjectsAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Projects.ListProjects, ProjectListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Update project. Update the project canonical directory, display metadata, and workspace commands.
    /// </summary>
    /// <param name = "projectId">The &apos;projectID&apos; route value.</param>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ProjectUpdateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>project.update</c>: <c>PATCH /api/project/{projectID}</c>.
    /// </remarks>
    public virtual Task<ProjectUpdateResponse> UpdateProjectAsync(string projectId, ProjectUpdateRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(projectId);
        return Pipeline.ExecuteAsync(OpenCodeHttpMethod.Patch, OpenCodeRoutes.Projects.UpdateProject(projectId), request ?? EmptyProjectUpdateRequest, OpenCodeJsonContext.Default.ProjectUpdateRequest, ProjectUpdateResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
