// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/credential&apos; responses onto &apos;CredentialCreateResponse&apos;.
/// </summary>
internal sealed class CredentialCreateResponseAdapter : ResponseAdapter<CredentialCreateResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status409Tags = ["ConflictError"];
    private CredentialCreateResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static CredentialCreateResponseAdapter Instance { get; } = new CredentialCreateResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        409 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override CredentialCreateResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Credential = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.CredentialCreateResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override CredentialCreateResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new CredentialCreateResponse
            {
                Status = status,
                Credential = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.CredentialCreateResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new CredentialCreateResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new CredentialCreateResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            409 => new CredentialCreateResponse(status, ReadTolerantError(rawBody, Status409Tags), rawBody),
            _ => new CredentialCreateResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
