// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/experimental/fs/write&apos; responses onto &apos;ExperimentalFsWriteResponse&apos;.
/// </summary>
internal sealed class ExperimentalFsWriteResponseAdapter : ResponseAdapter<ExperimentalFsWriteResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError"];
    private ExperimentalFsWriteResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ExperimentalFsWriteResponseAdapter Instance { get; } = new ExperimentalFsWriteResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override ExperimentalFsWriteResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.ExperimentalFsWriteResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ExperimentalFsWriteResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.ExperimentalFsWriteResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new ExperimentalFsWriteResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ExperimentalFsWriteResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new ExperimentalFsWriteResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new ExperimentalFsWriteResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static ExperimentalFsWriteResponse CreateSuccess(int status, ExperimentalFsWriteResponseEnvelope envelope) => new()
    {
        Status = status,
        File = envelope.Data,
        Location = envelope.Location
    };
}
