// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/experimental/session/{sessionID}/instructions/entries&apos; responses onto &apos;ExperimentalSessionInstructionsEntryListResponse&apos;.
/// </summary>
internal sealed class ExperimentalSessionInstructionsEntryListResponseAdapter : ResponseAdapter<ExperimentalSessionInstructionsEntryListResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "SessionNotFoundError"];
    private ExperimentalSessionInstructionsEntryListResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ExperimentalSessionInstructionsEntryListResponseAdapter Instance { get; } = new ExperimentalSessionInstructionsEntryListResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override ExperimentalSessionInstructionsEntryListResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        SessionInstructionsEntry = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.ExperimentalSessionInstructionsEntryListResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ExperimentalSessionInstructionsEntryListResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new ExperimentalSessionInstructionsEntryListResponse
            {
                Status = status,
                SessionInstructionsEntry = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.ExperimentalSessionInstructionsEntryListResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new ExperimentalSessionInstructionsEntryListResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ExperimentalSessionInstructionsEntryListResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new ExperimentalSessionInstructionsEntryListResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new ExperimentalSessionInstructionsEntryListResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
