// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/experimental/generate&apos; responses onto &apos;ExperimentalGenerateTextResponse&apos;.
/// </summary>
internal sealed class ExperimentalGenerateTextResponseAdapter : ResponseAdapter<ExperimentalGenerateTextResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private ExperimentalGenerateTextResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ExperimentalGenerateTextResponseAdapter Instance { get; } = new ExperimentalGenerateTextResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override ExperimentalGenerateTextResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        GenerateText = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.ExperimentalGenerateTextResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ExperimentalGenerateTextResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new ExperimentalGenerateTextResponse
            {
                Status = status,
                GenerateText = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.ExperimentalGenerateTextResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new ExperimentalGenerateTextResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ExperimentalGenerateTextResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new ExperimentalGenerateTextResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            503 => new ExperimentalGenerateTextResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new ExperimentalGenerateTextResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
