// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/experimental/mcp/{server}/connect&apos; responses onto &apos;ExperimentalMcpConnectResponse&apos;.
/// </summary>
internal sealed class ExperimentalMcpConnectResponseAdapter : ResponseAdapter<ExperimentalMcpConnectResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "McpServerNotFoundError"];
    private ExperimentalMcpConnectResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ExperimentalMcpConnectResponseAdapter Instance { get; } = new ExperimentalMcpConnectResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        204 => StatusVerdict.NoContentSuccess,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override ExperimentalMcpConnectResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ExperimentalMcpConnectResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new ExperimentalMcpConnectResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new ExperimentalMcpConnectResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ExperimentalMcpConnectResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new ExperimentalMcpConnectResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new ExperimentalMcpConnectResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
