// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;PUT /api/experimental/session/{sessionID}/instructions/entries/{key}&apos; responses onto &apos;ExperimentalSessionInstructionsEntryResponse&apos;.
/// </summary>
internal sealed class ExperimentalSessionInstructionsEntryResponseAdapter : ResponseAdapter<ExperimentalSessionInstructionsEntryResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "SessionNotFoundError"];
    private static readonly string[] Status413Tags = ["InstructionEntryValueTooLargeError"];
    private ExperimentalSessionInstructionsEntryResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ExperimentalSessionInstructionsEntryResponseAdapter Instance { get; } = new ExperimentalSessionInstructionsEntryResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        204 => StatusVerdict.NoContentSuccess,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        413 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override ExperimentalSessionInstructionsEntryResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ExperimentalSessionInstructionsEntryResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new ExperimentalSessionInstructionsEntryResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new ExperimentalSessionInstructionsEntryResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ExperimentalSessionInstructionsEntryResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new ExperimentalSessionInstructionsEntryResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            413 => new ExperimentalSessionInstructionsEntryResponse(status, ReadTolerantError(rawBody, Status413Tags), rawBody),
            _ => new ExperimentalSessionInstructionsEntryResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
