// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/fs/read/*&apos; responses onto &apos;FsReadResponse&apos;.
/// </summary>
internal sealed class FsReadResponseAdapter : ResponseAdapter<FsReadResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["FileNotFoundError", "LocationNotFoundError"];
    private FsReadResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static FsReadResponseAdapter Instance { get; } = new FsReadResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override FsReadResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => throw new InvalidOperationException("A binary success is adapted from its raw bytes, not from text.");
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override FsReadResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => throw new InvalidOperationException("A binary success is adapted from its raw bytes, not from text."),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new FsReadResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new FsReadResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new FsReadResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new FsReadResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    /// <summary>
    /// Gets a value indicating that the success body is raw bytes.
    /// </summary>
    public override bool BinarySuccess => true;

    /// <summary>
    /// Maps the raw success bytes and their content type onto the typed envelope.
    /// </summary>
    public override FsReadResponse AdaptBinary(int status, ReadOnlySpan<byte> body, string? contentType) => new()
    {
        Status = status,
        Content = body.ToArray(),
        ContentType = contentType
    };
}
