// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/integration/{integrationID}/connect/command/{attemptID}&apos; responses onto &apos;IntegrationCommandStatusResponse&apos;.
/// </summary>
internal sealed class IntegrationCommandStatusResponseAdapter : ResponseAdapter<IntegrationCommandStatusResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["IntegrationAttemptNotFoundError", "IntegrationNotFoundError", "LocationNotFoundError"];
    private IntegrationCommandStatusResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static IntegrationCommandStatusResponseAdapter Instance { get; } = new IntegrationCommandStatusResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override IntegrationCommandStatusResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.IntegrationCommandStatusResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override IntegrationCommandStatusResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.IntegrationCommandStatusResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new IntegrationCommandStatusResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new IntegrationCommandStatusResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new IntegrationCommandStatusResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new IntegrationCommandStatusResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static IntegrationCommandStatusResponse CreateSuccess(int status, IntegrationCommandStatusResponseEnvelope envelope) => new()
    {
        Status = status,
        CommandStatus = envelope.Data,
        Location = envelope.Location
    };
}
