// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/integration/{integrationID}/connect/oauth&apos; responses onto &apos;IntegrationOauthConnectResponse&apos;.
/// </summary>
internal sealed class IntegrationOauthConnectResponseAdapter : ResponseAdapter<IntegrationOauthConnectResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError"];
    private IntegrationOauthConnectResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static IntegrationOauthConnectResponseAdapter Instance { get; } = new IntegrationOauthConnectResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override IntegrationOauthConnectResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.IntegrationOauthConnectResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override IntegrationOauthConnectResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.IntegrationOauthConnectResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new IntegrationOauthConnectResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new IntegrationOauthConnectResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new IntegrationOauthConnectResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new IntegrationOauthConnectResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static IntegrationOauthConnectResponse CreateSuccess(int status, IntegrationOauthConnectResponseEnvelope envelope) => new()
    {
        Status = status,
        OauthConnect = envelope.Data,
        Location = envelope.Location
    };
}
