// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/pty/{ptyID}/connect-token&apos; responses onto &apos;PtyConnectTokenResponse&apos;.
/// </summary>
internal sealed class PtyConnectTokenResponseAdapter : ResponseAdapter<PtyConnectTokenResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status403Tags = ["ForbiddenError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "PtyNotFoundError"];
    private PtyConnectTokenResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static PtyConnectTokenResponseAdapter Instance { get; } = new PtyConnectTokenResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        403 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override PtyConnectTokenResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.PtyConnectTokenResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override PtyConnectTokenResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.PtyConnectTokenResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new PtyConnectTokenResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new PtyConnectTokenResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            403 => new PtyConnectTokenResponse(status, ReadTolerantError(rawBody, Status403Tags), rawBody),
            404 => new PtyConnectTokenResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new PtyConnectTokenResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static PtyConnectTokenResponse CreateSuccess(int status, PtyConnectTokenResponseEnvelope envelope) => new()
    {
        Status = status,
        ConnectToken = envelope.Data,
        Location = envelope.Location
    };
}
