// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;PUT /api/pty/{ptyID}&apos; responses onto &apos;PtyUpdateResponse&apos;.
/// </summary>
internal sealed class PtyUpdateResponseAdapter : ResponseAdapter<PtyUpdateResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "PtyNotFoundError"];
    private PtyUpdateResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static PtyUpdateResponseAdapter Instance { get; } = new PtyUpdateResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override PtyUpdateResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.PtyUpdateResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override PtyUpdateResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.PtyUpdateResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new PtyUpdateResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new PtyUpdateResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new PtyUpdateResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new PtyUpdateResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static PtyUpdateResponse CreateSuccess(int status, PtyUpdateResponseEnvelope envelope) => new()
    {
        Status = status,
        Pty = envelope.Data,
        Location = envelope.Location
    };
}
