// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/rpc/{rpcID}/{method}&apos; responses onto &apos;RpcCallResponse&apos;.
/// </summary>
internal sealed class RpcCallResponseAdapter : ResponseAdapter<RpcCallResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError", "RpcError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError"];
    private static readonly string[] Status500Tags = ["RpcInternalError"];
    private RpcCallResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static RpcCallResponseAdapter Instance { get; } = new RpcCallResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        500 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override RpcCallResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Call = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.RpcOutput)
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override RpcCallResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new RpcCallResponse
            {
                Status = status,
                Call = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.RpcOutput)
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new RpcCallResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new RpcCallResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new RpcCallResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            500 => new RpcCallResponse(status, ReadTolerantError(rawBody, Status500Tags), rawBody),
            _ => new RpcCallResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
