// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/session/{sessionID}/form&apos; responses onto &apos;SessionFormListResponse&apos;.
/// </summary>
internal sealed class SessionFormListResponseAdapter : ResponseAdapter<SessionFormListResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "SessionNotFoundError"];
    private SessionFormListResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionFormListResponseAdapter Instance { get; } = new SessionFormListResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionFormListResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Forms = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.SessionFormListResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionFormListResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new SessionFormListResponse
            {
                Status = status,
                Forms = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionFormListResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionFormListResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionFormListResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionFormListResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new SessionFormListResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
