// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/session/{sessionID}/diff&apos; responses onto &apos;SessionDiffResponse&apos;.
/// </summary>
internal sealed class SessionDiffResponseAdapter : ResponseAdapter<SessionDiffResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "MessageNotFoundError", "SessionNotFoundError"];
    private static readonly string[] Status500Tags = ["UnknownError"];
    private SessionDiffResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionDiffResponseAdapter Instance { get; } = new SessionDiffResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        500 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionDiffResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Diffs = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.SessionDiffResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionDiffResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new SessionDiffResponse
            {
                Status = status,
                Diffs = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionDiffResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionDiffResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionDiffResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionDiffResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            500 => new SessionDiffResponse(status, ReadTolerantError(rawBody, Status500Tags), rawBody),
            _ => new SessionDiffResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
