// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/session/{sessionID}/permission&apos; responses onto &apos;SessionPermissionListResponse&apos;.
/// </summary>
internal sealed class SessionPermissionListResponseAdapter : ResponseAdapter<SessionPermissionListResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "SessionNotFoundError"];
    private SessionPermissionListResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionPermissionListResponseAdapter Instance { get; } = new SessionPermissionListResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionPermissionListResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Requests = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.SessionPermissionListResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionPermissionListResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new SessionPermissionListResponse
            {
                Status = status,
                Requests = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionPermissionListResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionPermissionListResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionPermissionListResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionPermissionListResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new SessionPermissionListResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
