// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/session&apos; responses onto &apos;SessionCreateResponse&apos;.
/// </summary>
internal sealed class SessionCreateResponseAdapter : ResponseAdapter<SessionCreateResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["SessionNotFoundError"];
    private SessionCreateResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionCreateResponseAdapter Instance { get; } = new SessionCreateResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionCreateResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status,
        Session = ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.SessionCreateResponseEnvelope).Data
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionCreateResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => new SessionCreateResponse
            {
                Status = status,
                Session = ReadBarePayload(rawBody, OpenCodeJsonContext.Default.SessionCreateResponseEnvelope).Data
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionCreateResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionCreateResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionCreateResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new SessionCreateResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
