// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;DELETE /api/session/{sessionID}/revert&apos; responses onto &apos;SessionRevertClearResponse&apos;.
/// </summary>
internal sealed class SessionRevertClearResponseAdapter : ResponseAdapter<SessionRevertClearResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "SessionNotFoundError"];
    private static readonly string[] Status409Tags = ["SessionBusyError"];
    private static readonly string[] Status500Tags = ["UnknownError"];
    private SessionRevertClearResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static SessionRevertClearResponseAdapter Instance { get; } = new SessionRevertClearResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        204 => StatusVerdict.NoContentSuccess,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        409 => StatusVerdict.DeclaredError,
        500 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override SessionRevertClearResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override SessionRevertClearResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new SessionRevertClearResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new SessionRevertClearResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new SessionRevertClearResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new SessionRevertClearResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            409 => new SessionRevertClearResponse(status, ReadTolerantError(rawBody, Status409Tags), rawBody),
            500 => new SessionRevertClearResponse(status, ReadTolerantError(rawBody, Status500Tags), rawBody),
            _ => new SessionRevertClearResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
