// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;GET /api/shell/{id}&apos; responses onto &apos;ShellResponse&apos;.
/// </summary>
internal sealed class ShellResponseAdapter : ResponseAdapter<ShellResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError", "ShellNotFoundError"];
    private ShellResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static ShellResponseAdapter Instance { get; } = new ShellResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override ShellResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.ShellResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override ShellResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.ShellResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new ShellResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new ShellResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new ShellResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            _ => new ShellResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static ShellResponse CreateSuccess(int status, ShellResponseEnvelope envelope) => new()
    {
        Status = status,
        Shell = envelope.Data,
        Location = envelope.Location
    };
}
