// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/vcs/init&apos; responses onto &apos;VcsInitResponse&apos;.
/// </summary>
internal sealed class VcsInitResponseAdapter : ResponseAdapter<VcsInitResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError"];
    private static readonly string[] Status409Tags = ["ConflictError"];
    private static readonly string[] Status501Tags = ["VcsInitNotSupportedError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private VcsInitResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static VcsInitResponseAdapter Instance { get; } = new VcsInitResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        204 => StatusVerdict.NoContentSuccess,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        409 => StatusVerdict.DeclaredError,
        501 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override VcsInitResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => new()
    {
        Status = status
    };
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override VcsInitResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            204 => new VcsInitResponse
            {
                Status = status
            },
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new VcsInitResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new VcsInitResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new VcsInitResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            409 => new VcsInitResponse(status, ReadTolerantError(rawBody, Status409Tags), rawBody),
            501 => new VcsInitResponse(status, ReadTolerantError(rawBody, Status501Tags), rawBody),
            503 => new VcsInitResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new VcsInitResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }
}
