// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Internal.ResponseAdapters;
/// <summary>
/// Adapts the &apos;POST /api/websearch&apos; responses onto &apos;WebsearchQueryResponse&apos;.
/// </summary>
internal sealed class WebsearchQueryResponseAdapter : ResponseAdapter<WebsearchQueryResponse>
{
    private static readonly string[] Status400Tags = ["InvalidRequestError"];
    private static readonly string[] Status401Tags = ["UnauthorizedError"];
    private static readonly string[] Status404Tags = ["LocationNotFoundError"];
    private static readonly string[] Status503Tags = ["ServiceUnavailableError"];
    private WebsearchQueryResponseAdapter()
    {
    }

    /// <summary>
    /// Gets the shared adapter instance.
    /// </summary>
    public static WebsearchQueryResponseAdapter Instance { get; } = new WebsearchQueryResponseAdapter();

    /// <summary>
    /// Classifies a status under this operation&apos;s pinned contract.
    /// </summary>
    public override StatusVerdict Classify(int status) => status switch
    {
        200 => StatusVerdict.Success,
        >= 200 and < 300 => StatusVerdict.UndeclaredSuccess,
        400 => StatusVerdict.DeclaredError,
        401 => StatusVerdict.DeclaredError,
        404 => StatusVerdict.DeclaredError,
        503 => StatusVerdict.DeclaredError,
        _ => StatusVerdict.UndeclaredError
    };
    /// <summary>
    /// Maps the declared UTF-8 success body onto the typed envelope.
    /// </summary>
    public override WebsearchQueryResponse AdaptSuccess(int status, ReadOnlySpan<byte> utf8Body) => CreateSuccess(status, ReadBarePayload(utf8Body, OpenCodeJsonContext.Default.WebsearchQueryResponseEnvelope));
    /// <summary>
    /// Maps one buffered response onto the typed envelope.
    /// </summary>
    public override WebsearchQueryResponse Adapt(int status, string rawBody)
    {
        ArgumentNullException.ThrowIfNull(rawBody);
        return status switch
        {
            200 => CreateSuccess(status, ReadBarePayload(rawBody, OpenCodeJsonContext.Default.WebsearchQueryResponseEnvelope)),
            >= 200 and < 300 => throw StatusVerdictFailures.UndeclaredSuccess(status),
            400 => new WebsearchQueryResponse(status, ReadTolerantError(rawBody, Status400Tags), rawBody),
            401 => new WebsearchQueryResponse(status, ReadTolerantError(rawBody, Status401Tags), rawBody),
            404 => new WebsearchQueryResponse(status, ReadTolerantError(rawBody, Status404Tags), rawBody),
            503 => new WebsearchQueryResponse(status, ReadTolerantError(rawBody, Status503Tags), rawBody),
            _ => new WebsearchQueryResponse(status, ReadTolerantError(rawBody, null), rawBody)
        };
    }

    private static WebsearchQueryResponse CreateSuccess(int status, WebsearchQueryResponseEnvelope envelope) => new()
    {
        Status = status,
        Query = envelope.Data,
        Location = envelope.Location
    };
}
