// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;FileSystemClient&apos; collection client.
/// </summary>
public class FileSystemClient
{
    private readonly Pipeline? _pipeline;
    internal FileSystemClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected FileSystemClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("FileSystemClient", "Pipeline");

    /// <summary>
    /// Find files. Find recursively ranked filesystem entries relative to the requested location.
    /// </summary>
    /// <param name = "request">The request shaping the query; its required members have no server default.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;FsFindResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>fs.find</c>: <c>GET /api/fs/find</c>.
    /// </remarks>
    public virtual Task<FsFindResponse> FindEntriesAsync(FsFindRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.FileSystem.FindEntries(request), FsFindResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List directory. List direct children using an absolute path or a path relative to the requested location, including parents and siblings outside its directory. Entry paths remain relative to the requested location; listing does not switch locations.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;FsListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>fs.list</c>: <c>GET /api/fs/list</c>.
    /// </remarks>
    public virtual Task<FsListResponse> ListEntriesAsync(FsListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.FileSystem.ListEntries(request), FsListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Read file. Serve one file relative to the requested location.
    /// </summary>
    /// <param name = "request">The request shaping the query; its required members have no server default.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;FsReadResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>fs.read</c>: <c>GET /api/fs/read/*</c>.
    /// </remarks>
    public virtual Task<FsReadResponse> ReadFileAsync(FsReadRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.FileSystem.ReadFile(request), FsReadResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
