// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;RpcClient&apos; collection client.
/// </summary>
public class RpcClient
{
    private static readonly RpcCallRequest EmptyRpcCallRequest = new();
    private readonly Pipeline? _pipeline;
    internal RpcClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected RpcClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("RpcClient", "Pipeline");

    /// <summary>
    /// Call a plugin RPC. Dispatch a method to the currently registered RPC at the requested location.
    /// </summary>
    /// <param name = "rpcId">The &apos;rpcID&apos; route value.</param>
    /// <param name = "method">The &apos;method&apos; route value.</param>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;RpcCallResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>rpc.call</c>: <c>POST /api/rpc/{rpcID}/{method}</c>.
    /// </remarks>
    public virtual Task<RpcCallResponse> CallAsync(string rpcId, string method, RpcCallRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(rpcId);
        ArgumentException.ThrowIfNullOrEmpty(method);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Rpc.Call(rpcId, method, request), request ?? EmptyRpcCallRequest, OpenCodeJsonContext.Default.RpcCallRequest, RpcCallResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
