// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;PermissionsClient&apos; collection client.
/// </summary>
public class PermissionsClient
{
    private readonly Pipeline? _pipeline;
    internal PermissionsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected PermissionsClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("PermissionsClient", "Pipeline");

    /// <summary>
    /// List pending permission requests. Retrieve pending permission requests for a location.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PermissionRequestListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>permission.request.list</c>: <c>GET /api/permission/request</c>.
    /// </remarks>
    public virtual Task<PermissionRequestListResponse> ListRequestsAsync(PermissionRequestListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Permissions.ListRequests(request), PermissionRequestListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List saved permissions. Retrieve saved permissions, optionally filtered by project.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PermissionSavedListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>permission.saved.list</c>: <c>GET /api/permission/saved</c>.
    /// </remarks>
    public virtual Task<PermissionSavedListResponse> ListSavedAsync(PermissionSavedListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Permissions.ListSaved(request), PermissionSavedListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Remove saved permission. Remove a saved permission by ID.
    /// </summary>
    /// <param name = "id">The &apos;id&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;PermissionSavedRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>permission.saved.remove</c>: <c>DELETE /api/permission/saved/{id}</c>.
    /// </remarks>
    public virtual Task<PermissionSavedRemoveResponse> RemoveSavedAsync(string id, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(id);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Permissions.RemoveSaved(id), PermissionSavedRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
