// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;ExperimentalClient&apos; collection client.
/// </summary>
public class ExperimentalClient
{
    private readonly Pipeline? _pipeline;
    internal ExperimentalClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected ExperimentalClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("ExperimentalClient", "Pipeline");

    /// <summary>
    /// Activate skill. Activate a skill for a session by appending a skill message and resuming execution.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionSkillResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.skill</c>: <c>POST /api/experimental/session/{sessionID}/skill</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionSkillResponse> ActivateSessionSkillAsync(string sessionId, ExperimentalSessionSkillRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(sessionId);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.ActivateSessionSkill(sessionId), request, OpenCodeJsonContext.Default.ExperimentalSessionSkillRequest, ExperimentalSessionSkillResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Add wellknown integration. Discover and persist an experimental wellknown integration source.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalIntegrationWellknownAddResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.integration.wellknown.add</c>: <c>POST /api/experimental/integration/wellknown</c>.
    /// </remarks>
    public virtual Task<ExperimentalIntegrationWellknownAddResponse> AddIntegrationWellknownAsync(ExperimentalIntegrationWellknownAddRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.AddIntegrationWellknown(request), request, OpenCodeJsonContext.Default.ExperimentalIntegrationWellknownAddRequest, ExperimentalIntegrationWellknownAddResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Add MCP server. Add an MCP server at runtime or replace an existing one, connecting it immediately.
    /// </summary>
    /// <param name = "server">The &apos;server&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalMcpAddResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.mcp.add</c>: <c>PUT /api/experimental/mcp/{server}</c>.
    /// </remarks>
    public virtual Task<ExperimentalMcpAddResponse> AddMcpServerAsync(string server, ExperimentalMcpAddRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(server);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Put, OpenCodeRoutes.Experimental.AddMcpServer(server, request), request, OpenCodeJsonContext.Default.ExperimentalMcpAddRequest, ExperimentalMcpAddResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Connect MCP server. Connect an MCP server at runtime, overriding a disabled configuration until restart.
    /// </summary>
    /// <param name = "server">The &apos;server&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalMcpConnectResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.mcp.connect</c>: <c>POST /api/experimental/mcp/{server}/connect</c>.
    /// </remarks>
    public virtual Task<ExperimentalMcpConnectResponse> ConnectMcpServerAsync(string server, ExperimentalMcpConnectRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(server);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.ConnectMcpServer(server, request), ExperimentalMcpConnectResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Disconnect MCP server. Disconnect an MCP server at runtime, removing its tools until reconnected.
    /// </summary>
    /// <param name = "server">The &apos;server&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalMcpDisconnectResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.mcp.disconnect</c>: <c>POST /api/experimental/mcp/{server}/disconnect</c>.
    /// </remarks>
    public virtual Task<ExperimentalMcpDisconnectResponse> DisconnectMcpServerAsync(string server, ExperimentalMcpDisconnectRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(server);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.DisconnectMcpServer(server, request), ExperimentalMcpDisconnectResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Generate text. Run one stateless model generation using the server&apos;s base configuration and return the assistant text. Uses the base configuration&apos;s default model when none is specified.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalGenerateTextResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.generate.text</c>: <c>POST /api/experimental/generate</c>.
    /// </remarks>
    public virtual Task<ExperimentalGenerateTextResponse> GenerateTextAsync(ExperimentalGenerateTextRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.GenerateText, request, OpenCodeJsonContext.Default.ExperimentalGenerateTextRequest, ExperimentalGenerateTextResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get V1 migration status. Return the progress of the V1 to V2 session history migration.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalMigrationV1StatusResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.migration.v1.status</c>: <c>GET /api/experimental/migration/v1</c>.
    /// </remarks>
    public virtual Task<ExperimentalMigrationV1StatusResponse> GetMigrationV1StatusAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Experimental.GetMigrationV1Status, ExperimentalMigrationV1StatusResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Export session. Export a complete projected session transcript.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionExportResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.export</c>: <c>GET /api/experimental/session/{sessionID}/export</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionExportResponse> GetSessionExportAsync(string sessionId, ExperimentalSessionExportRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(sessionId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Experimental.GetSessionExport(sessionId, request), ExperimentalSessionExportResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session statistics. Aggregate local session activity, usage, and tool reliability for a time range.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionStatsResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.stats</c>: <c>GET /api/experimental/session/stats</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionStatsResponse> GetSessionStatsAsync(ExperimentalSessionStatsRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Experimental.GetSessionStats(request), ExperimentalSessionStatsResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Import session. Import a projected session transcript at the requested location. If parentID is supplied, the parent session must already exist; import parents before children.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionImportResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.import</c>: <c>POST /api/experimental/session/import</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionImportResponse> ImportSessionAsync(ExperimentalSessionImportRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.ImportSession, request, OpenCodeJsonContext.Default.ExperimentalSessionImportRequest, ExperimentalSessionImportResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List instruction entries. List API-managed instruction entries attached to the session.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionInstructionsEntryListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.instructions.entry.list</c>: <c>GET /api/experimental/session/{sessionID}/instructions/entries</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionInstructionsEntryListResponse> ListSessionInstructionsEntryAsync(string sessionId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(sessionId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Experimental.ListSessionInstructionsEntry(sessionId), ExperimentalSessionInstructionsEntryListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Remove MCP server. Stop an MCP server and remove it from the runtime set until restart.
    /// </summary>
    /// <param name = "server">The &apos;server&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalMcpRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.mcp.remove</c>: <c>DELETE /api/experimental/mcp/{server}</c>.
    /// </remarks>
    public virtual Task<ExperimentalMcpRemoveResponse> RemoveMcpServerAsync(string server, ExperimentalMcpRemoveRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(server);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Experimental.RemoveMcpServer(server, request), ExperimentalMcpRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Remove instruction entry. Remove one instruction entry; the removal is announced to the model at the next step boundary.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <param name = "key">The &apos;key&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionInstructionsEntryRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.instructions.entry.remove</c>: <c>DELETE /api/experimental/session/{sessionID}/instructions/entries/{key}</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionInstructionsEntryRemoveResponse> RemoveSessionInstructionsEntryAsync(string sessionId, string key, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(sessionId);
        ArgumentException.ThrowIfNullOrEmpty(key);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Experimental.RemoveSessionInstructionsEntry(sessionId, key), ExperimentalSessionInstructionsEntryRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Put instruction entry. Attach or replace one durable instruction entry. Changes announce as updates at the next step boundary.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <param name = "key">The &apos;key&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionInstructionsEntryResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 413) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.instructions.entry.put</c>: <c>PUT /api/experimental/session/{sessionID}/instructions/entries/{key}</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionInstructionsEntryResponse> SetSessionInstructionsEntryAsync(string sessionId, string key, ExperimentalSessionInstructionsEntryRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(sessionId);
        ArgumentException.ThrowIfNullOrEmpty(key);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Put, OpenCodeRoutes.Experimental.SetSessionInstructionsEntry(sessionId, key), request, OpenCodeJsonContext.Default.ExperimentalSessionInstructionsEntryRequest, ExperimentalSessionInstructionsEntryResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Update global configuration. Patch supported fields in the highest-precedence global configuration document.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalConfigUpdateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.config.update</c>: <c>PATCH /api/experimental/config</c>.
    /// </remarks>
    public virtual Task<ExperimentalConfigUpdateResponse> UpdateConfigAsync(ExperimentalConfigUpdateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(OpenCodeHttpMethod.Patch, OpenCodeRoutes.Experimental.UpdateConfig, request, OpenCodeJsonContext.Default.ExperimentalConfigUpdateRequest, ExperimentalConfigUpdateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Wait for session. Wait for a session agent loop to become idle.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalSessionWaitResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.session.wait</c>: <c>POST /api/experimental/session/{sessionID}/wait</c>.
    /// </remarks>
    public virtual Task<ExperimentalSessionWaitResponse> WaitForSessionAsync(string sessionId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(sessionId);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.WaitForSession(sessionId), ExperimentalSessionWaitResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Write file. Write the raw request body to an absolute path or a path relative to the requested location, creating parent directories, and return the resolved absolute path. Unlike read, the target is not confined to the location. Experimental: may change without compatibility guarantees.
    /// </summary>
    /// <param name = "request">The request shaping the query; its required members have no server default.</param>
    /// <param name = "content">The bytes to send, read from the stream&apos;s current position to its end; the stream is neither disposed nor rewound.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ExperimentalFsWriteResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>experimental.fs.write</c>: <c>POST /api/experimental/fs/write</c>.
    /// </remarks>
    public virtual Task<ExperimentalFsWriteResponse> WriteFileAsync(ExperimentalFsWriteRequest request, Stream content, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(content);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Experimental.WriteFile(request), content, ExperimentalFsWriteResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
