// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;AgentsClient&apos; collection client.
/// </summary>
public class AgentsClient
{
    private readonly Pipeline? _pipeline;
    internal AgentsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected AgentsClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("AgentsClient", "Pipeline");

    /// <summary>
    /// Get agent. Retrieve a single currently registered agent.
    /// </summary>
    /// <param name = "agentId">The &apos;agentID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;AgentResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>agent.get</c>: <c>GET /api/agent/{agentID}</c>.
    /// </remarks>
    public virtual Task<AgentResponse> GetAgentAsync(string agentId, AgentRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(agentId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Agents.GetAgent(agentId, request), AgentResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List agents. Retrieve currently registered agents.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;AgentListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>agent.list</c>: <c>GET /api/agent</c>.
    /// </remarks>
    public virtual Task<AgentListResponse> ListAgentsAsync(AgentListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Agents.ListAgents(request), AgentListResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
