// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config lsp entry structural union.
/// </summary>
[JsonConverter(typeof(ConfigLspEntryJsonConverter))]
public sealed record ConfigLspEntry
{
    private readonly object _value;
    private ConfigLspEntry(ConfigLspEntryKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ConfigLspEntryKind Kind { get; }
    /// <summary>
    /// Gets the config lsp disabled value.
    /// </summary>
    public ConfigLspDisabled ConfigLspDisabled => GetValue<ConfigLspDisabled>(ConfigLspEntryKind.ConfigLspDisabled);

    /// <summary>
    /// Creates a config lsp entry from its config lsp disabled arm.
    /// </summary>
    public static ConfigLspEntry FromConfigLspDisabled(ConfigLspDisabled value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ConfigLspEntry(ConfigLspEntryKind.ConfigLspDisabled, value);
    }

    /// <summary>
    /// Gets the config lsp server value.
    /// </summary>
    public ConfigLspServer ConfigLspServer => GetValue<ConfigLspServer>(ConfigLspEntryKind.ConfigLspServer);

    /// <summary>
    /// Creates a config lsp entry from its config lsp server arm.
    /// </summary>
    public static ConfigLspEntry FromConfigLspServer(ConfigLspServer value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ConfigLspEntry(ConfigLspEntryKind.ConfigLspServer, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ConfigLspEntryKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ConfigLspEntry FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ConfigLspEntry(ConfigLspEntryKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ConfigLspEntryKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm, an unrecognized token masked; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ConfigLspEntry), Kind.ToString(), Kind is ConfigLspEntryKind.Unknown ? RecordPrinter.Redacted : _value);
}
