// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config info formatter structural union.
/// </summary>
[JsonConverter(typeof(ConfigInfoFormatterJsonConverter))]
public sealed record ConfigInfoFormatter
{
    private readonly object _value;
    private ConfigInfoFormatter(ConfigInfoFormatterKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ConfigInfoFormatterKind Kind { get; }
    /// <summary>
    /// Gets the boolean value.
    /// </summary>
    public bool Boolean => GetValue<bool>(ConfigInfoFormatterKind.Boolean);

    /// <summary>
    /// Creates a config info formatter from its boolean arm.
    /// </summary>
    public static ConfigInfoFormatter FromBoolean(bool value)
    {
        return new ConfigInfoFormatter(ConfigInfoFormatterKind.Boolean, value);
    }

    /// <summary>
    /// Gets the config formatter entry dictionary value.
    /// </summary>
    public IReadOnlyDictionary<string, ConfigFormatterEntry> ConfigFormatterEntryDictionary => GetValue<IReadOnlyDictionary<string, ConfigFormatterEntry>>(ConfigInfoFormatterKind.ConfigFormatterEntryDictionary);

    /// <summary>
    /// Creates a config info formatter from its config formatter entry dictionary arm.
    /// </summary>
    public static ConfigInfoFormatter FromConfigFormatterEntryDictionary(IReadOnlyDictionary<string, ConfigFormatterEntry> value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ConfigInfoFormatter(ConfigInfoFormatterKind.ConfigFormatterEntryDictionary, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ConfigInfoFormatterKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ConfigInfoFormatter FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ConfigInfoFormatter(ConfigInfoFormatterKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ConfigInfoFormatterKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm, an unrecognized token masked; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ConfigInfoFormatter), Kind.ToString(), Kind is ConfigInfoFormatterKind.Unknown ? RecordPrinter.Redacted : _value);
}
