// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported config info experimental policies action values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<ConfigInfoExperimentalPoliciesAction>))]
public enum ConfigInfoExperimentalPoliciesAction
{
    /// <summary>
    /// Represents the &apos;provider.use&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("provider.use")]
    ProviderUse,
    /// <summary>
    /// Represents the &apos;tool.use&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("tool.use")]
    ToolUse,
    /// <summary>
    /// Represents the &apos;integration.use&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("integration.use")]
    IntegrationUse
}
