// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config model capabilities value.
/// </summary>
public sealed record ConfigModelCapabilities
{
    /// <summary>
    /// Gets the tools value.
    /// </summary>
    [JsonPropertyName("tools")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Tools { get; init; }

    /// <summary>
    /// Gets the input value.
    /// </summary>
    [JsonPropertyName("input")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Input { get; init; }

    /// <summary>
    /// Gets the output value.
    /// </summary>
    [JsonPropertyName("output")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Output { get; init; }
}
