// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk.Models;
/// <summary>
/// Identifies the active arm of ConfigProviderSettingsHeaderTimeout.
/// </summary>
public enum ConfigProviderSettingsHeaderTimeoutKind
{
    /// <summary>
    /// Represents the number arm.
    /// </summary>
    Number,
    /// <summary>
    /// Represents the boolean arm.
    /// </summary>
    Boolean,
    /// <summary>
    /// Represents the unknown arm.
    /// </summary>
    Unknown
}
