// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config formatter entry value.
/// </summary>
public sealed record ConfigFormatterEntry
{
    /// <summary>
    /// Gets the disabled value.
    /// </summary>
    [JsonPropertyName("disabled")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Disabled { get; init; }

    /// <summary>
    /// Gets the command value.
    /// </summary>
    [JsonPropertyName("command")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Command { get; init; }

    /// <summary>
    /// Gets the environment value.
    /// </summary>
    [JsonPropertyName("environment")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, string>? Environment { get; init; }

    /// <summary>
    /// Gets the extensions value.
    /// </summary>
    [JsonPropertyName("extensions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Extensions { get; init; }

    /// <summary>
    /// Prints the record&apos;s members with its secret members masked.
    /// </summary>
    public override string ToString() => RecordPrinter.Format(nameof(ConfigFormatterEntry), ("Disabled", Disabled), ("Command", Command), ("Environment", RecordPrinter.Redact(Environment)), ("Extensions", Extensions));
}
