// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config info lsp structural union.
/// </summary>
[JsonConverter(typeof(ConfigInfoLspJsonConverter))]
public sealed record ConfigInfoLsp
{
    private readonly object _value;
    private ConfigInfoLsp(ConfigInfoLspKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ConfigInfoLspKind Kind { get; }
    /// <summary>
    /// Gets the boolean value.
    /// </summary>
    public bool Boolean => GetValue<bool>(ConfigInfoLspKind.Boolean);

    /// <summary>
    /// Creates a config info lsp from its boolean arm.
    /// </summary>
    public static ConfigInfoLsp FromBoolean(bool value)
    {
        return new ConfigInfoLsp(ConfigInfoLspKind.Boolean, value);
    }

    /// <summary>
    /// Gets the config lsp entry dictionary value.
    /// </summary>
    public IReadOnlyDictionary<string, ConfigLspEntry> ConfigLspEntryDictionary => GetValue<IReadOnlyDictionary<string, ConfigLspEntry>>(ConfigInfoLspKind.ConfigLspEntryDictionary);

    /// <summary>
    /// Creates a config info lsp from its config lsp entry dictionary arm.
    /// </summary>
    public static ConfigInfoLsp FromConfigLspEntryDictionary(IReadOnlyDictionary<string, ConfigLspEntry> value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return new ConfigInfoLsp(ConfigInfoLspKind.ConfigLspEntryDictionary, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ConfigInfoLspKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ConfigInfoLsp FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ConfigInfoLsp(ConfigInfoLspKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ConfigInfoLspKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm, an unrecognized token masked; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ConfigInfoLsp), Kind.ToString(), Kind is ConfigInfoLspKind.Unknown ? RecordPrinter.Redacted : _value);
}
