// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a config provider settings chunk timeout structural union.
/// </summary>
[JsonConverter(typeof(ConfigProviderSettingsChunkTimeoutJsonConverter))]
public sealed record ConfigProviderSettingsChunkTimeout
{
    private readonly object _value;
    private ConfigProviderSettingsChunkTimeout(ConfigProviderSettingsChunkTimeoutKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ConfigProviderSettingsChunkTimeoutKind Kind { get; }
    /// <summary>
    /// Gets the number value.
    /// </summary>
    public double Number => GetValue<double>(ConfigProviderSettingsChunkTimeoutKind.Number);

    /// <summary>
    /// Creates a config provider settings chunk timeout from its number arm.
    /// </summary>
    public static ConfigProviderSettingsChunkTimeout FromNumber(double value)
    {
        return new ConfigProviderSettingsChunkTimeout(ConfigProviderSettingsChunkTimeoutKind.Number, value);
    }

    /// <summary>
    /// Gets the boolean value.
    /// </summary>
    public bool Boolean => GetValue<bool>(ConfigProviderSettingsChunkTimeoutKind.Boolean);

    /// <summary>
    /// Creates a config provider settings chunk timeout from its boolean arm.
    /// </summary>
    public static ConfigProviderSettingsChunkTimeout FromBoolean(bool value)
    {
        return new ConfigProviderSettingsChunkTimeout(ConfigProviderSettingsChunkTimeoutKind.Boolean, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ConfigProviderSettingsChunkTimeoutKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ConfigProviderSettingsChunkTimeout FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ConfigProviderSettingsChunkTimeout(ConfigProviderSettingsChunkTimeoutKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ConfigProviderSettingsChunkTimeoutKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ConfigProviderSettingsChunkTimeout), Kind.ToString(), _value);
}
