// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Defines the supported connection credential info method values.
/// </summary>
[JsonConverter(typeof(StrictJsonStringEnumConverter<ConnectionCredentialInfoMethod>))]
public enum ConnectionCredentialInfoMethod
{
    /// <summary>
    /// Represents the &apos;key&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("key")]
    Key,
    /// <summary>
    /// Represents the &apos;oauth&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("oauth")]
    Oauth,
    /// <summary>
    /// Represents the &apos;external&apos; wire value.
    /// </summary>
    [JsonStringEnumMemberName("external")]
    External
}
