// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a connection env info value.
/// </summary>
public sealed record ConnectionEnvInfo : IConnectionInfo
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "env";

    /// <summary>
    /// Gets the name value.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ConnectionStatus? Status { get; init; }
}
