// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a credential entry value.
/// </summary>
public sealed record CredentialEntry
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Gets the integration id value.
    /// </summary>
    [JsonPropertyName("integrationID")]
    public required string IntegrationId { get; init; }

    /// <summary>
    /// Gets the label value.
    /// </summary>
    [JsonPropertyName("label")]
    public required string Label { get; init; }

    /// <summary>
    /// Gets the active value.
    /// </summary>
    [JsonPropertyName("active")]
    public required bool Active { get; init; }

    /// <summary>
    /// Gets the value value.
    /// </summary>
    [JsonPropertyName("value")]
    public required ICredentialValue Value { get; init; }
}
