// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a credential o auth value.
/// </summary>
public sealed record CredentialOAuth : ICredentialValue
{
    /// <summary>
    /// Gets the type value.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "oauth";

    /// <summary>
    /// Gets the method id value.
    /// </summary>
    [JsonPropertyName("methodID")]
    public required string MethodId { get; init; }

    /// <summary>
    /// Gets the refresh value.
    /// </summary>
    [JsonPropertyName("refresh")]
    public required string Refresh { get; init; }

    /// <summary>
    /// Gets the access value.
    /// </summary>
    [JsonPropertyName("access")]
    public required string Access { get; init; }

    /// <summary>
    /// Gets the expires value.
    /// </summary>
    [JsonPropertyName("expires")]
    public required long Expires { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyDictionary<string, JsonElement>? Metadata { get; init; }

    /// <summary>
    /// Prints the record&apos;s members with its secret members masked.
    /// </summary>
    public override string ToString() => RecordPrinter.Format(nameof(CredentialOAuth), ("Type", Type), ("MethodId", MethodId), ("Refresh", RecordPrinter.Redact(Refresh)), ("Access", RecordPrinter.Redact(Access)), ("Expires", Expires), ("Metadata", Metadata));
}
