// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a credential create request value.
/// </summary>
public sealed record CredentialCreateRequest
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Id { get; init; }

    /// <summary>
    /// Gets the integration id value.
    /// </summary>
    [JsonPropertyName("integrationID")]
    public required string IntegrationId { get; init; }

    /// <summary>
    /// Gets the label value.
    /// </summary>
    [JsonPropertyName("label")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Label { get; init; }

    /// <summary>
    /// Gets the value value.
    /// </summary>
    [JsonPropertyName("value")]
    public required ICredentialValue Value { get; init; }

    /// <summary>
    /// Gets the activate value.
    /// </summary>
    [JsonPropertyName("activate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Activate { get; init; }
}
