// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a form state cancelled value.
/// </summary>
public sealed record FormStateCancelled : IFormState
{
    /// <summary>
    /// Gets the status value.
    /// </summary>
    [JsonPropertyName("status")]
    public string Status => "cancelled";

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Message { get; init; }
}
