// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a connection info union.
/// </summary>
[JsonConverter(typeof(ConnectionInfoJsonConverter))]
public interface IConnectionInfo
{
    /// <summary>
    /// Gets the &apos;type&apos; union marker.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; }

    /// <summary>
    /// Gets the status value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownConnectionInfo.
    /// </summary>
    [JsonPropertyName("status")]
    public ConnectionStatus? Status { get; }
}
