// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a credential value union.
/// </summary>
[JsonConverter(typeof(CredentialValueJsonConverter))]
public interface ICredentialValue
{
    /// <summary>
    /// Gets the &apos;type&apos; union marker.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type { get; }

    /// <summary>
    /// Gets the metadata value. Every declared variant carries it; the value is null when the payload is an unrecognized variant preserved as UnknownCredentialValue.
    /// </summary>
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, JsonElement>? Metadata { get; }
}
