// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a integration connect external request value.
/// </summary>
public sealed record IntegrationConnectExternalRequest
{
    /// <summary>
    /// Gets the method id value.
    /// </summary>
    [JsonPropertyName("methodID")]
    public required string MethodId { get; init; }

    /// <summary>
    /// Gets the answer value.
    /// </summary>
    [JsonPropertyName("answer")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfFormValueDictionaryJsonConverter))]
    public Optional<IReadOnlyDictionary<string, FormValue>?> Answer { get; init; }

    /// <summary>
    /// Gets the label value.
    /// </summary>
    [JsonPropertyName("label")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Label { get; init; }

    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    [JsonIgnore]
    public LocationSelector? Location { get; init; }
}
