// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a model compatibility value.
/// </summary>
public sealed record ModelCompatibility
{
    /// <summary>
    /// Gets the reasoning field value.
    /// </summary>
    [JsonPropertyName("reasoningField")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ReasoningField { get; init; }

    /// <summary>
    /// Gets the require reasoning value.
    /// </summary>
    [JsonPropertyName("requireReasoning")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? RequireReasoning { get; init; }

    /// <summary>
    /// Gets the max tokens field value.
    /// </summary>
    [JsonPropertyName("maxTokensField")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ModelMaxTokensField? MaxTokensField { get; init; }

    /// <summary>
    /// Gets the require finish reason value.
    /// </summary>
    [JsonPropertyName("requireFinishReason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? RequireFinishReason { get; init; }

    /// <summary>
    /// Gets the require assistant after tool value.
    /// </summary>
    [JsonPropertyName("requireAssistantAfterTool")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? RequireAssistantAfterTool { get; init; }

    /// <summary>
    /// Gets the supports prompt cache key value.
    /// </summary>
    [JsonPropertyName("supportsPromptCacheKey")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SupportsPromptCacheKey { get; init; }

    /// <summary>
    /// Gets the supports thinking block binding value.
    /// </summary>
    [JsonPropertyName("supportsThinkingBlockBinding")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SupportsThinkingBlockBinding { get; init; }

    /// <summary>
    /// Gets the supports effort updates value.
    /// </summary>
    [JsonPropertyName("supportsEffortUpdates")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? SupportsEffortUpdates { get; init; }
}
