// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a provider settings value.
/// </summary>
public sealed record ProviderSettings
{
    /// <summary>
    /// Gets the timeout value.
    /// </summary>
    [JsonPropertyName("timeout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProviderSettingsTimeout? Timeout { get; init; }

    /// <summary>
    /// Gets the header timeout value.
    /// </summary>
    [JsonPropertyName("headerTimeout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProviderSettingsHeaderTimeout? HeaderTimeout { get; init; }

    /// <summary>
    /// Gets the chunk timeout value.
    /// </summary>
    [JsonPropertyName("chunkTimeout")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProviderSettingsChunkTimeout? ChunkTimeout { get; init; }

    /// <summary>
    /// Gets the compaction value.
    /// </summary>
    [JsonPropertyName("compaction")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IProviderCompaction? Compaction { get; init; }

    /// <summary>
    /// Gets the transport value.
    /// </summary>
    [JsonPropertyName("transport")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ProviderTransport? Transport { get; init; }

    /// <summary>
    /// Gets the members the pinned document leaves open, keyed by wire name; empty when the body carried none.
    /// </summary>
    [JsonIgnore]
    public IReadOnlyDictionary<string, JsonElement> AdditionalProperties
    {
        get => OpenMembers ?? EmptyOpenMembers.Instance;
        init
        {
            ArgumentNullException.ThrowIfNull(value);
            OpenMembers = value.ToDictionary(static pair => pair.Key, static pair => pair.Value, StringComparer.Ordinal);
        }
    }

    /// <summary>
    /// Gets or sets the serializer&apos;s writable bag behind AdditionalProperties, created on the first open member; the public member is the read-only view.
    /// </summary>
    [JsonExtensionData]
    [JsonInclude]
    internal Dictionary<string, JsonElement>? OpenMembers { get; set; }

    /// <summary>
    /// Prints the record&apos;s members with its secret members masked.
    /// </summary>
    public override string ToString() => RecordPrinter.Format(nameof(ProviderSettings), ("Timeout", Timeout), ("HeaderTimeout", HeaderTimeout), ("ChunkTimeout", ChunkTimeout), ("Compaction", Compaction), ("Transport", Transport), ("AdditionalProperties", RecordPrinter.RedactEntries(AdditionalProperties)));
}
