// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a provider settings header timeout structural union.
/// </summary>
[JsonConverter(typeof(ProviderSettingsHeaderTimeoutJsonConverter))]
public sealed record ProviderSettingsHeaderTimeout
{
    private readonly object _value;
    private ProviderSettingsHeaderTimeout(ProviderSettingsHeaderTimeoutKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ProviderSettingsHeaderTimeoutKind Kind { get; }
    /// <summary>
    /// Gets the number value.
    /// </summary>
    public double Number => GetValue<double>(ProviderSettingsHeaderTimeoutKind.Number);

    /// <summary>
    /// Creates a provider settings header timeout from its number arm.
    /// </summary>
    public static ProviderSettingsHeaderTimeout FromNumber(double value)
    {
        return new ProviderSettingsHeaderTimeout(ProviderSettingsHeaderTimeoutKind.Number, value);
    }

    /// <summary>
    /// Gets the boolean value.
    /// </summary>
    public bool Boolean => GetValue<bool>(ProviderSettingsHeaderTimeoutKind.Boolean);

    /// <summary>
    /// Creates a provider settings header timeout from its boolean arm.
    /// </summary>
    public static ProviderSettingsHeaderTimeout FromBoolean(bool value)
    {
        return new ProviderSettingsHeaderTimeout(ProviderSettingsHeaderTimeoutKind.Boolean, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ProviderSettingsHeaderTimeoutKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ProviderSettingsHeaderTimeout FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ProviderSettingsHeaderTimeout(ProviderSettingsHeaderTimeoutKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ProviderSettingsHeaderTimeoutKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ProviderSettingsHeaderTimeout), Kind.ToString(), _value);
}
