// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a provider settings chunk timeout structural union.
/// </summary>
[JsonConverter(typeof(ProviderSettingsChunkTimeoutJsonConverter))]
public sealed record ProviderSettingsChunkTimeout
{
    private readonly object _value;
    private ProviderSettingsChunkTimeout(ProviderSettingsChunkTimeoutKind kind, object value)
    {
        Kind = kind;
        _value = value;
    }

    /// <summary>
    /// Gets the active structural union arm.
    /// </summary>
    public ProviderSettingsChunkTimeoutKind Kind { get; }
    /// <summary>
    /// Gets the number value.
    /// </summary>
    public double Number => GetValue<double>(ProviderSettingsChunkTimeoutKind.Number);

    /// <summary>
    /// Creates a provider settings chunk timeout from its number arm.
    /// </summary>
    public static ProviderSettingsChunkTimeout FromNumber(double value)
    {
        return new ProviderSettingsChunkTimeout(ProviderSettingsChunkTimeoutKind.Number, value);
    }

    /// <summary>
    /// Gets the boolean value.
    /// </summary>
    public bool Boolean => GetValue<bool>(ProviderSettingsChunkTimeoutKind.Boolean);

    /// <summary>
    /// Creates a provider settings chunk timeout from its boolean arm.
    /// </summary>
    public static ProviderSettingsChunkTimeout FromBoolean(bool value)
    {
        return new ProviderSettingsChunkTimeout(ProviderSettingsChunkTimeoutKind.Boolean, value);
    }

    /// <summary>
    /// Gets the preserved raw payload for an unrecognized token kind.
    /// </summary>
    public JsonElement Unknown => GetValue<JsonElement>(ProviderSettingsChunkTimeoutKind.Unknown);

    /// <summary>
    /// Creates a structural union value preserving an unrecognized JSON token.
    /// </summary>
    public static ProviderSettingsChunkTimeout FromUnknown(JsonElement value)
    {
        if (value.ValueKind == JsonValueKind.Undefined)
        {
            throw new ArgumentException("The unknown value must be a parsed JSON element.", nameof(value));
        }

        return new ProviderSettingsChunkTimeout(ProviderSettingsChunkTimeoutKind.Unknown, value.Clone());
    }

    private T GetValue<T>(ProviderSettingsChunkTimeoutKind expected)
    {
        if (Kind != expected)
        {
            throw new InvalidOperationException("The structural value does not contain the requested arm.");
        }

        return (T)_value;
    }

    /// <summary>
    /// Prints the kind and the active arm; the inactive arms throw by design.
    /// </summary>
    public override string ToString() => StructuralUnionPrinter.Format(nameof(ProviderSettingsChunkTimeout), Kind.ToString(), _value);
}
