// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a server info value.
/// </summary>
public sealed record ServerInfo
{
    /// <summary>
    /// Gets the version value.
    /// </summary>
    [JsonPropertyName("version")]
    public required string Version { get; init; }

    /// <summary>
    /// Gets the pid value.
    /// </summary>
    [JsonPropertyName("pid")]
    public required long Pid { get; init; }

    /// <summary>
    /// Gets the urls value.
    /// </summary>
    [JsonPropertyName("urls")]
    public required IReadOnlyList<string> Urls { get; init; }

    /// <summary>
    /// Gets the paths value.
    /// </summary>
    [JsonPropertyName("paths")]
    public required ServerInfoPaths Paths { get; init; }

    /// <summary>
    /// Gets the capabilities value.
    /// </summary>
    [JsonPropertyName("capabilities")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ServerInfoCapabilities? Capabilities { get; init; }
}
