// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a server info capabilities value.
/// </summary>
public sealed record ServerInfoCapabilities
{
    /// <summary>
    /// Gets the persistent pty value.
    /// </summary>
    [JsonPropertyName("persistentPty")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? PersistentPty { get; init; }
}
