// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session structured error response value.
/// </summary>
public sealed record SessionStructuredErrorResponse
{
    /// <summary>
    /// Gets the body value.
    /// </summary>
    [JsonPropertyName("body")]
    public required string Body { get; init; }
}
