// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session environment request value.
/// </summary>
public sealed record SessionEnvironmentRequest
{
    /// <summary>
    /// Gets the variables value.
    /// </summary>
    [JsonPropertyName("variables")]
    public required IReadOnlyDictionary<string, string> Variables { get; init; }

    /// <summary>
    /// Prints the record&apos;s members with its secret members masked.
    /// </summary>
    public override string ToString() => RecordPrinter.Format(nameof(SessionEnvironmentRequest), ("Variables", RecordPrinter.Redact(Variables)));
}
