// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a session create request value.
/// </summary>
public sealed record SessionCreateRequest
{
    /// <summary>
    /// Gets the id value.
    /// </summary>
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Id { get; init; }

    /// <summary>
    /// Gets the parent id value.
    /// </summary>
    [JsonPropertyName("parentID")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> ParentId { get; init; }

    /// <summary>
    /// Gets the title value.
    /// </summary>
    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Title { get; init; }

    /// <summary>
    /// Gets the agent value.
    /// </summary>
    [JsonPropertyName("agent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfStringJsonConverter))]
    public Optional<string?> Agent { get; init; }

    /// <summary>
    /// Gets the model value.
    /// </summary>
    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfModelRefJsonConverter))]
    public Optional<ModelRef?> Model { get; init; }

    /// <summary>
    /// Gets the location value.
    /// </summary>
    [JsonPropertyName("location")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfLocationPublicRefJsonConverter))]
    public Optional<LocationPublicRef?> Location { get; init; }

    /// <summary>
    /// Gets the metadata value.
    /// </summary>
    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfJsonElementDictionaryJsonConverter))]
    public Optional<IReadOnlyDictionary<string, JsonElement>?> Metadata { get; init; }

    /// <summary>
    /// Gets the permissions value.
    /// </summary>
    [JsonPropertyName("permissions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [JsonConverter(typeof(OptionalOfPermissionRuleListJsonConverter))]
    public Optional<IReadOnlyList<PermissionRule>?> Permissions { get; init; }
}
