// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Preserves an unknown config entry payload.
/// </summary>
[JsonConverter(typeof(UnknownConfigEntryJsonConverter))]
public sealed record UnknownConfigEntry : IConfigEntry
{
    private readonly string _marker;
    /// <summary>
    /// Initializes an unknown union value from its marker and raw payload.
    /// </summary>
    [JsonConstructor]
    public UnknownConfigEntry(string type, JsonElement payload)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(type);
        if (payload.ValueKind is JsonValueKind.Undefined)
        {
            throw new ArgumentException("The payload must be a parsed JSON element.", nameof(payload));
        }

        UnionPayloadGuard.Instance.RequireString(payload, "type", type);
        _marker = type;
        Payload = payload.Clone();
    }

    /// <summary>
    /// Gets the unrecognized &apos;type&apos; marker.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => _marker;
    /// <summary>
    /// Gets the preserved raw JSON payload.
    /// </summary>
    public JsonElement Payload { get; }

    /// <summary>
    /// Prints the marker with the preserved payload masked, since a known arm of this union carries a secret.
    /// </summary>
    public override string ToString() => RecordPrinter.Format(nameof(UnknownConfigEntry), ("Type", Type), ("Payload", RecordPrinter.Redact(Payload)));
}
