// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Internal.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Preserves an unknown open code error payload.
/// </summary>
[JsonConverter(typeof(UnknownOpenCodeErrorJsonConverter))]
public sealed record UnknownOpenCodeError : IOpenCodeError
{
    private readonly string _marker;
    /// <summary>
    /// Initializes an unknown union value from its marker and raw payload.
    /// </summary>
    [JsonConstructor]
    public UnknownOpenCodeError(string tag, JsonElement payload)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(tag);
        if (payload.ValueKind is JsonValueKind.Undefined)
        {
            throw new ArgumentException("The payload must be a parsed JSON element.", nameof(payload));
        }

        UnionPayloadGuard.Instance.RequireString(payload, "_tag", tag);
        _marker = tag;
        Payload = payload.Clone();
    }

    /// <summary>
    /// Gets the unrecognized &apos;_tag&apos; marker.
    /// </summary>
    [JsonPropertyName("_tag")]
    public string Tag => _marker;
    /// <summary>
    /// Gets the preserved raw JSON payload.
    /// </summary>
    public JsonElement Payload { get; }
}
