// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json.Serialization;

namespace OpenCode.Sdk.Models;
/// <summary>
/// Represents a vcs init not supported error value.
/// </summary>
public sealed record VcsInitNotSupportedError : IOpenCodeError
{
    /// <summary>
    /// Gets the tag value.
    /// </summary>
    [JsonPropertyName("_tag")]
    public string Tag => "VcsInitNotSupportedError";

    /// <summary>
    /// Gets the provider id value.
    /// </summary>
    [JsonPropertyName("providerID")]
    public required string ProviderId { get; init; }

    /// <summary>
    /// Gets the message value.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }
}
