// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;VcsClient&apos; collection client.
/// </summary>
public class VcsClient
{
    private readonly Pipeline? _pipeline;
    internal VcsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected VcsClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("VcsClient", "Pipeline");

    /// <summary>
    /// VCS review base. Infer a local review base from named branch creation history, or the repository default only when currently on that branch. Returns null before the first commit or when the provider lacks base metadata; ambiguous Git history requires an explicit base on diff requests.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;VcsBaseResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>vcs.base</c>: <c>GET /api/vcs/base</c>.
    /// </remarks>
    public virtual Task<VcsBaseResponse> GetBaseAsync(VcsBaseRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Vcs.GetBase(request), VcsBaseResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// VCS diff. Diff HEAD to the working copy (working), the base merge-base to the working copy (branch), or the base merge-base to HEAD (committed). Omitting base preserves repository-default comparison; supplying it overrides the comparison without saving it.
    /// </summary>
    /// <param name = "request">The request shaping the query; its required members have no server default.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;VcsDiffResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>vcs.diff</c>: <c>GET /api/vcs/diff</c>.
    /// </remarks>
    public virtual Task<VcsDiffResponse> GetDiffAsync(VcsDiffRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Vcs.GetDiff(request), VcsDiffResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// VCS status. List uncommitted working-copy changes relative to the requested location.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;VcsStatusResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>vcs.status</c>: <c>GET /api/vcs/status</c>.
    /// </remarks>
    public virtual Task<VcsStatusResponse> GetStatusAsync(VcsStatusRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Vcs.GetStatus(request), VcsStatusResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// VCS info. Get current and default branch information for the requested location.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;VcsResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>vcs.get</c>: <c>GET /api/vcs</c>.
    /// </remarks>
    public virtual Task<VcsResponse> GetVcsAsync(VcsRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Vcs.GetVcs(request), VcsResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Initialize VCS repository. Initialize a repository using the selected VCS provider in a markerless project&apos;s directory and refresh its location services. Omitting provider defaults to git; built-in git and hg providers support initialization. An unknown provider returns 400; a registered provider without init returns 501.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;VcsInitResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409, 501, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>vcs.init</c>: <c>POST /api/vcs/init</c>.
    /// </remarks>
    public virtual Task<VcsInitResponse> InitializeRepositoryAsync(VcsInitRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Vcs.InitializeRepository(request), VcsInitResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// VCS branches. List local and remote branches available at the requested location.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;VcsBranchListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>vcs.branch.list</c>: <c>GET /api/vcs/branch</c>.
    /// </remarks>
    public virtual Task<VcsBranchListResponse> ListBranchesAsync(VcsBranchListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Vcs.ListBranches(request), VcsBranchListResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
