// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
namespace OpenCode.Sdk;
/// <summary>
/// Shapes the &apos;POST /api/vcs/init&apos; query.
/// </summary>
public sealed record VcsInitRequest
{
    /// <summary>
    /// Gets the &apos;location&apos; query value; the server default applies when unset.
    /// </summary>
    public LocationSelector? Location { get; init; }
    /// <summary>
    /// Gets the &apos;provider&apos; query value; the server default applies when unset.
    /// </summary>
    public string? Provider { get; init; }
}
