// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;WebsearchClient&apos; collection client.
/// </summary>
public class WebsearchClient
{
    private readonly Pipeline? _pipeline;
    internal WebsearchClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected WebsearchClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("WebsearchClient", "Pipeline");

    /// <summary>
    /// List web search providers. Return the registered web search providers.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;WebsearchProvidersResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>websearch.providers</c>: <c>GET /api/websearch/provider</c>.
    /// </remarks>
    public virtual Task<WebsearchProvidersResponse> GetProvidersAsync(WebsearchProvidersRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Websearch.GetProviders(request), WebsearchProvidersResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Search the web. Run one web search through the selected provider. Specify a provider to override the configured default.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;WebsearchQueryResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>websearch.query</c>: <c>POST /api/websearch</c>.
    /// </remarks>
    public virtual Task<WebsearchQueryResponse> QueryAsync(WebsearchQueryRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Websearch.Query(request), request, OpenCodeJsonContext.Default.WebsearchQueryRequest, WebsearchQueryResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
