// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// A bound &apos;IntegrationClient&apos; handle; it holds an immutable identifier and the shared pipeline.
/// </summary>
public class IntegrationClient
{
    private static readonly IntegrationOauthCompleteRequest EmptyIntegrationOauthCompleteRequest = new();
    private readonly Pipeline? _pipeline;
    private readonly string? _integrationId;
    internal IntegrationClient(Pipeline pipeline, string integrationId)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
        if (integrationId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
        }

        _pipeline = pipeline;
        _integrationId = integrationId;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected IntegrationClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("IntegrationClient", "Pipeline");
    private string IntegrationId => _integrationId ?? throw MockSeam.CreateError("IntegrationClient", "IntegrationId");

    /// <summary>
    /// Begin command connection. Start a command authentication attempt.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationCommandConnectResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.command.connect</c>: <c>POST /api/integration/{integrationID}/connect/command</c>.
    /// </remarks>
    public virtual Task<IntegrationCommandConnectResponse> BeginCommandConnectionAsync(IntegrationCommandConnectRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Integrations.BeginCommandConnection(IntegrationId, request), request, OpenCodeJsonContext.Default.IntegrationCommandConnectRequest, IntegrationCommandConnectResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Begin OAuth connection. Start an OAuth attempt and return the authorization details.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationOauthConnectResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.oauth.connect</c>: <c>POST /api/integration/{integrationID}/connect/oauth</c>.
    /// </remarks>
    public virtual Task<IntegrationOauthConnectResponse> BeginOauthConnectionAsync(IntegrationOauthConnectRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Integrations.BeginOauthConnection(IntegrationId, request), request, OpenCodeJsonContext.Default.IntegrationOauthConnectRequest, IntegrationOauthConnectResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Cancel command connection. Cancel a command authentication attempt and terminate its process.
    /// </summary>
    /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationCommandCancelResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.command.cancel</c>: <c>DELETE /api/integration/{integrationID}/connect/command/{attemptID}</c>.
    /// </remarks>
    public virtual Task<IntegrationCommandCancelResponse> CancelCommandConnectionAsync(string attemptId, IntegrationCommandCancelRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(attemptId);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Integrations.CancelCommandConnection(IntegrationId, attemptId, request), IntegrationCommandCancelResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Cancel OAuth connection. Cancel an OAuth attempt and release its resources.
    /// </summary>
    /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationOauthCancelResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.oauth.cancel</c>: <c>DELETE /api/integration/{integrationID}/connect/oauth/{attemptID}</c>.
    /// </remarks>
    public virtual Task<IntegrationOauthCancelResponse> CancelOauthConnectionAsync(string attemptId, IntegrationOauthCancelRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(attemptId);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Integrations.CancelOauthConnection(IntegrationId, attemptId, request), IntegrationOauthCancelResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Complete OAuth connection. Complete a code-based OAuth attempt and store the resulting credential.
    /// </summary>
    /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationOauthCompleteResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.oauth.complete</c>: <c>POST /api/integration/{integrationID}/connect/oauth/{attemptID}/complete</c>.
    /// </remarks>
    public virtual Task<IntegrationOauthCompleteResponse> CompleteOauthConnectionAsync(string attemptId, IntegrationOauthCompleteRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(attemptId);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Integrations.CompleteOauthConnection(IntegrationId, attemptId, request), request ?? EmptyIntegrationOauthCompleteRequest, OpenCodeJsonContext.Default.IntegrationOauthCompleteRequest, IntegrationOauthCompleteResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Connect with key. Run a key authentication method and store the resulting credential.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationConnectKeyResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.connect.key</c>: <c>POST /api/integration/{integrationID}/connect/key</c>.
    /// </remarks>
    public virtual Task<IntegrationConnectKeyResponse> ConnectWithKeyAsync(IntegrationConnectKeyRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Integrations.ConnectWithKey(IntegrationId, request), request, OpenCodeJsonContext.Default.IntegrationConnectKeyRequest, IntegrationConnectKeyResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get integration. Retrieve one integration and its authentication methods.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.get</c>: <c>GET /api/integration/{integrationID}</c>.
    /// </remarks>
    public virtual Task<IntegrationResponse> GetAsync(IntegrationRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Integrations.Get(IntegrationId, request), IntegrationResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get command attempt status. Poll the current status and output of a command authentication attempt.
    /// </summary>
    /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationCommandStatusResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.command.status</c>: <c>GET /api/integration/{integrationID}/connect/command/{attemptID}</c>.
    /// </remarks>
    public virtual Task<IntegrationCommandStatusResponse> GetCommandStatusAsync(string attemptId, IntegrationCommandStatusRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(attemptId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Integrations.GetCommandStatus(IntegrationId, attemptId, request), IntegrationCommandStatusResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get OAuth attempt status. Poll the current status of an OAuth attempt.
    /// </summary>
    /// <param name = "attemptId">The &apos;attemptID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationOauthStatusResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.oauth.status</c>: <c>GET /api/integration/{integrationID}/connect/oauth/{attemptID}</c>.
    /// </remarks>
    public virtual Task<IntegrationOauthStatusResponse> GetOauthStatusAsync(string attemptId, IntegrationOauthStatusRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(attemptId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Integrations.GetOauthStatus(IntegrationId, attemptId, request), IntegrationOauthStatusResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
