// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/integration/{integrationID}/connect/external&apos; operation.
/// </summary>
public sealed record IntegrationConnectExternalResponse : OpenCodeResponse
{
    /// <summary>
    /// Initializes a success instance of the &apos;IntegrationConnectExternalResponse&apos; envelope.
    /// </summary>
    public IntegrationConnectExternalResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal IntegrationConnectExternalResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
    }
}
