// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;IntegrationsClient&apos; collection client.
/// </summary>
public class IntegrationsClient
{
    private readonly Pipeline? _pipeline;
    internal IntegrationsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected IntegrationsClient()
    {
    }

    /// <summary>
    /// Gets a bound &apos;IntegrationClient&apos;; the handle never caches server state.
    /// </summary>
    /// <param name = "integrationId">The &apos;integrationID&apos; route value.</param>
    /// <returns>The bound &apos;IntegrationClient&apos;.</returns>
    public virtual IntegrationClient GetIntegrationClient(string integrationId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(integrationId);
        if (integrationId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(integrationId));
        }

        return new IntegrationClient(Pipeline, integrationId);
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("IntegrationsClient", "Pipeline");

    /// <summary>
    /// List integrations. Retrieve available integrations and their authentication methods.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;IntegrationListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>integration.list</c>: <c>GET /api/integration</c>.
    /// </remarks>
    public virtual Task<IntegrationListResponse> ListIntegrationsAsync(IntegrationListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Integrations.ListIntegrations(request), IntegrationListResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
