// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class ConfigProviderSettingsHeaderTimeoutJsonConverter : JsonConverter<ConfigProviderSettingsHeaderTimeout>
{
    public override ConfigProviderSettingsHeaderTimeout Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        return reader.TokenType switch
        {
            JsonTokenType.Number => ConfigProviderSettingsHeaderTimeout.FromNumber(reader.GetDouble()),
            JsonTokenType.True => ConfigProviderSettingsHeaderTimeout.FromBoolean(reader.GetBoolean()),
            JsonTokenType.False => ConfigProviderSettingsHeaderTimeout.FromBoolean(reader.GetBoolean()),
            JsonTokenType.None => throw new JsonException("JSON token 'None' cannot start this structural union value."),
            JsonTokenType.StartObject => ReadUnknown(ref reader),
            JsonTokenType.EndObject => throw new JsonException("JSON token 'EndObject' cannot start this structural union value."),
            JsonTokenType.StartArray => ReadUnknown(ref reader),
            JsonTokenType.EndArray => throw new JsonException("JSON token 'EndArray' cannot start this structural union value."),
            JsonTokenType.PropertyName => throw new JsonException("JSON token 'PropertyName' cannot start this structural union value."),
            JsonTokenType.Comment => throw new JsonException("JSON token 'Comment' cannot start this structural union value."),
            JsonTokenType.String => ReadUnknown(ref reader),
            JsonTokenType.Null => throw new JsonException("JSON token 'Null' cannot start this structural union value."),
            _ => throw new JsonException("The JSON token kind is not recognized.")
        };
    }

    public override void Write(Utf8JsonWriter writer, ConfigProviderSettingsHeaderTimeout value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        switch (value.Kind)
        {
            case ConfigProviderSettingsHeaderTimeoutKind.Number:
                writer.WriteNumberValue(value.Number);
                break;
            case ConfigProviderSettingsHeaderTimeoutKind.Boolean:
                writer.WriteBooleanValue(value.Boolean);
                break;
            case ConfigProviderSettingsHeaderTimeoutKind.Unknown:
                value.Unknown.WriteTo(writer);
                break;
            default:
                throw new JsonException("The structural union kind is not recognized.");
        }
    }

    private static ConfigProviderSettingsHeaderTimeout ReadUnknown(ref Utf8JsonReader reader)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        return ConfigProviderSettingsHeaderTimeout.FromUnknown(document.RootElement);
    }
}
