// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class CredentialValueJsonConverter : JsonConverter<ICredentialValue>
{
    private static readonly FrozenDictionary<string, Type> TypesByTag = new Dictionary<string, Type>(StringComparer.Ordinal)
    {
        ["key"] = typeof(CredentialKey),
        ["oauth"] = typeof(CredentialOAuth)
    }.ToFrozenDictionary(StringComparer.Ordinal);
    private static readonly UnionDiscriminatorReader DiscriminatorReader = new();
    public override ICredentialValue Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        if (DiscriminatorReader.TryFindKnown(ref reader, "type", "CredentialValue", TypesByTag, out var targetType, out var marker))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for CredentialValue.");
            return JsonSerializer.Deserialize(ref reader, typeInfo) as ICredentialValue ?? throw new JsonException("The CredentialValue payload deserialized to null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        return new UnknownCredentialValue(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, ICredentialValue value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownCredentialValue unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for CredentialValue.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
