// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Collections.Frozen;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class OpenCodeErrorJsonConverter : JsonConverter<IOpenCodeError>
{
    private static readonly FrozenDictionary<string, Type> TypesByTag = new Dictionary<string, Type>(StringComparer.Ordinal)
    {
        ["AgentNotFoundError"] = typeof(AgentNotFoundError),
        ["CommandExecutionError"] = typeof(CommandExecutionError),
        ["CommandNotFoundError"] = typeof(CommandNotFoundError),
        ["ConflictError"] = typeof(ConflictError),
        ["FileNotFoundError"] = typeof(FileNotFoundError),
        ["ForbiddenError"] = typeof(ForbiddenError),
        ["FormAlreadySettledError"] = typeof(FormAlreadySettledError),
        ["FormInvalidAnswerError"] = typeof(FormInvalidAnswerError),
        ["FormNotFoundError"] = typeof(FormNotFoundError),
        ["InstructionEntryValueTooLargeError"] = typeof(InstructionEntryValueTooLargeError),
        ["IntegrationAttemptNotFoundError"] = typeof(IntegrationAttemptNotFoundError),
        ["IntegrationMethodNotFoundError"] = typeof(IntegrationMethodNotFoundError),
        ["IntegrationNotFoundError"] = typeof(IntegrationNotFoundError),
        ["InvalidCursorError"] = typeof(InvalidCursorError),
        ["InvalidRequestError"] = typeof(InvalidRequestError),
        ["LocationNotFoundError"] = typeof(LocationNotFoundError),
        ["McpServerNotFoundError"] = typeof(McpServerNotFoundError),
        ["MessageNotFoundError"] = typeof(MessageNotFoundError),
        ["PermissionNotFoundError"] = typeof(PermissionNotFoundError),
        ["ProjectNotFoundError"] = typeof(ProjectNotFoundError),
        ["ProviderNotFoundError"] = typeof(ProviderNotFoundError),
        ["PtyNotFoundError"] = typeof(PtyNotFoundError),
        ["RpcError"] = typeof(RpcError),
        ["RpcInternalError"] = typeof(RpcInternalError),
        ["ServiceUnavailableError"] = typeof(ServiceUnavailableError),
        ["SessionBusyError"] = typeof(SessionBusyError),
        ["SessionNotFoundError"] = typeof(SessionNotFoundError),
        ["ShellNotFoundError"] = typeof(ShellNotFoundError),
        ["SkillNotFoundError"] = typeof(SkillNotFoundError),
        ["UnauthorizedError"] = typeof(UnauthorizedError),
        ["UnknownError"] = typeof(UnknownError),
        ["VcsInitNotSupportedError"] = typeof(VcsInitNotSupportedError),
        ["WorktreeError"] = typeof(WorktreeError)
    }.ToFrozenDictionary(StringComparer.Ordinal);
    private static readonly UnionDiscriminatorReader DiscriminatorReader = new();
    public override IOpenCodeError Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        if (DiscriminatorReader.TryFindKnown(ref reader, "_tag", "OpenCodeError", TypesByTag, out var targetType, out var marker))
        {
            var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(targetType) ?? throw new JsonException("The generated context has no metadata for OpenCodeError.");
            return JsonSerializer.Deserialize(ref reader, typeInfo) as IOpenCodeError ?? throw new JsonException("The OpenCodeError payload deserialized to null.");
        }

        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        return new UnknownOpenCodeError(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, IOpenCodeError value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        if (value is UnknownOpenCodeError unknown)
        {
            unknown.Payload.WriteTo(writer);
            return;
        }

        var typeInfo = OpenCodeJsonContext.Default.GetTypeInfo(value.GetType()) ?? throw new JsonException("The generated context has no metadata for OpenCodeError.");
        JsonSerializer.Serialize(writer, value, typeInfo);
    }
}
