// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk.Internal.Serialization;

internal sealed class UnknownOpenCodeErrorJsonConverter : JsonConverter<UnknownOpenCodeError>
{
    public override UnknownOpenCodeError Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(typeToConvert);
        ArgumentNullException.ThrowIfNull(options);
        using var document = JsonDocument.ParseValue(ref reader);
        var payload = document.RootElement;
        if (payload.ValueKind != JsonValueKind.Object)
        {
            throw new JsonException("The OpenCodeError payload must be a JSON object.");
        }

        if (!payload.TryGetProperty("_tag", out var markerElement))
        {
            throw new JsonException("The OpenCodeError payload must contain '_tag'.");
        }

        if (markerElement.ValueKind != JsonValueKind.String)
        {
            throw new JsonException("The '_tag' marker must be a string.");
        }

        var marker = markerElement.GetString();
        if (marker is null || string.IsNullOrWhiteSpace(marker))
        {
            throw new JsonException("The '_tag' marker must be a non-empty string.");
        }

        return new UnknownOpenCodeError(marker, payload);
    }

    public override void Write(Utf8JsonWriter writer, UnknownOpenCodeError value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(value);
        ArgumentNullException.ThrowIfNull(options);
        value.Payload.WriteTo(writer);
    }
}
