// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.Pagination;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Internal.StreamAdapters;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// A bound &apos;SessionClient&apos; handle; it holds an immutable identifier and the shared pipeline.
/// </summary>
public class SessionClient
{
    private static readonly SessionCompactRequest EmptySessionCompactRequest = new();
    private static readonly SessionForkRequest EmptySessionForkRequest = new();
    private static readonly SessionUpdateRequest EmptySessionUpdateRequest = new();
    private readonly Pipeline? _pipeline;
    private readonly string? _sessionId;
    internal SessionClient(Pipeline pipeline, string sessionId)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
        if (sessionId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
        }

        _pipeline = pipeline;
        _sessionId = sessionId;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected SessionClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("SessionClient", "Pipeline");
    private string SessionId => _sessionId ?? throw MockSeam.CreateError("SessionClient", "SessionId");

    /// <summary>
    /// Add synthetic message. Durably admit synthetic session input and schedule execution unless resume is false.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionSyntheticResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.synthetic</c>: <c>POST /api/session/{sessionID}/synthetic</c>.
    /// </remarks>
    public virtual Task<SessionSyntheticResponse> AddSyntheticMessageAsync(SessionSyntheticRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.AddSyntheticMessage(SessionId), request, OpenCodeJsonContext.Default.SessionSyntheticRequest, SessionSyntheticResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Cancel form. Cancel a pending form, optionally telling the asker why it was not answered.
    /// </summary>
    /// <param name = "formId">The &apos;formID&apos; route value.</param>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionFormCancelResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.form.cancel</c>: <c>DELETE /api/session/{sessionID}/form/{formID}</c>.
    /// </remarks>
    public virtual Task<SessionFormCancelResponse> CancelFormAsync(string formId, SessionFormCancelRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(formId);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Sessions.CancelForm(SessionId, formId, request), SessionFormCancelResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Cancel inbox input. Cancel an inbox item that has not yet been delivered. Unavailable items are a no-op.
    /// </summary>
    /// <param name = "inboxId">The &apos;inboxID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionInboxCancelResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.inbox.cancel</c>: <c>DELETE /api/session/{sessionID}/inbox/{inboxID}</c>.
    /// </remarks>
    public virtual Task<SessionInboxCancelResponse> CancelInboxAsync(string inboxId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(inboxId);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Sessions.CancelInbox(SessionId, inboxId), SessionInboxCancelResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Clear staged revert
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionRevertClearResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.revert.clear</c>: <c>DELETE /api/session/{sessionID}/revert</c>.
    /// </remarks>
    public virtual Task<SessionRevertClearResponse> ClearRevertAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Sessions.ClearRevert(SessionId), SessionRevertClearResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Commit staged revert
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionRevertCommitResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.revert.commit</c>: <c>POST /api/session/{sessionID}/revert/commit</c>.
    /// </remarks>
    public virtual Task<SessionRevertCommitResponse> CommitRevertAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.CommitRevert(SessionId), SessionRevertCommitResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Compact session. Durably admit a session compaction request. Steers by default: it runs at the next step boundary instead of waiting behind queued prompts.
    /// </summary>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionCompactResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.compact</c>: <c>POST /api/session/{sessionID}/compact</c>.
    /// </remarks>
    public virtual Task<SessionCompactResponse> CompactAsync(SessionCompactRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.Compact(SessionId), request ?? EmptySessionCompactRequest, OpenCodeJsonContext.Default.SessionCompactRequest, SessionCompactResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Create session form. Create a form for a session.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionFormCreateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.form.create</c>: <c>POST /api/session/{sessionID}/form</c>.
    /// </remarks>
    public virtual Task<SessionFormCreateResponse> CreateFormAsync(SessionFormCreateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.CreateForm(SessionId), request, OpenCodeJsonContext.Default.SessionFormCreateRequest, SessionFormCreateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Create permission request. Evaluate and, when approval is required, create a permission request for a session.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionPermissionCreateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.permission.create</c>: <c>POST /api/session/{sessionID}/permission</c>.
    /// </remarks>
    public virtual Task<SessionPermissionCreateResponse> CreatePermissionAsync(SessionPermissionCreateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.CreatePermission(SessionId), request, OpenCodeJsonContext.Default.SessionPermissionCreateRequest, SessionPermissionCreateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Fork session. Create a child session by copying projected history before a message. Omit before to copy the full history.
    /// </summary>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionForkResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.fork</c>: <c>POST /api/session/{sessionID}/fork</c>.
    /// </remarks>
    public virtual Task<SessionForkResponse> ForkAsync(SessionForkRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.Fork(SessionId), request ?? EmptySessionForkRequest, OpenCodeJsonContext.Default.SessionForkRequest, SessionForkResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Generate text from session context. Generate transient text from the current session context without mutating session history.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionGenerateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.generate</c>: <c>POST /api/session/{sessionID}/generate</c>.
    /// </remarks>
    public virtual Task<SessionGenerateResponse> GenerateTextAsync(SessionGenerateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.GenerateText(SessionId), request, OpenCodeJsonContext.Default.SessionGenerateRequest, SessionGenerateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session. Retrieve a session by ID.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.get</c>: <c>GET /api/session/{sessionID}</c>.
    /// </remarks>
    public virtual Task<SessionResponse> GetAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.Get(SessionId), SessionResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session context. Retrieve the active context messages for a session (all messages after the last compaction).
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionContextResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.context</c>: <c>GET /api/session/{sessionID}/context</c>.
    /// </remarks>
    public virtual Task<SessionContextResponse> GetContextAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetContext(SessionId), SessionContextResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Diff session turns. Structured per-file diffs of the files a turn changed. A turn runs from the first prompt after the session was last idle until its next idle marker, so prompts steered in while it was busy belong to the same turn; `to` extends the range through a later turn. Compares the range&apos;s first recorded snapshot with its last; a step still running in the active session compares against the working copy. Ranges that span a location change are rejected. In sessions without any idle marker, a prompt&apos;s turn spans until the next user message.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionDiffResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.diff</c>: <c>GET /api/session/{sessionID}/diff</c>.
    /// </remarks>
    public virtual Task<SessionDiffResponse> GetDiffAsync(SessionDiffRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetDiff(SessionId, request), SessionDiffResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session form. Retrieve a form and its current state for a session.
    /// </summary>
    /// <param name = "formId">The &apos;formID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionFormResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.form.get</c>: <c>GET /api/session/{sessionID}/form/{formID}</c>.
    /// </remarks>
    public virtual Task<SessionFormResponse> GetFormAsync(string formId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(formId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetForm(SessionId, formId), SessionFormResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Read the session log. Experimental durable session event log. Reads events after an exclusive aggregate sequence and continues with live events when follow=true.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ISessionLogItem&apos; stream.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned a declared error status (declared: 400, 401, 404); streaming API errors always throw.</exception>
    /// <exception cref = "OpenCodeStreamFailureException">The opened stream reported a schema-valid failure with a typed cause.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached, the stream could not be read, or a frame or failure cause was malformed.</exception>
    /// <remarks>
    /// Operation <c>session.log</c>: <c>GET /api/experimental/session/{sessionID}/log</c>.
    /// </remarks>
    public virtual IAsyncEnumerable<ISessionLogItem> GetLogAsync(SessionLogRequest? request = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteStreamAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetLog(SessionId, request), SessionLogResponseStreamAdapter.Instance, cancellationToken);
    }

    /// <summary>
    /// Get session message. Retrieve one projected message owned by the Session.
    /// </summary>
    /// <param name = "messageId">The &apos;messageID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionMessageResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.message.get</c>: <c>GET /api/session/{sessionID}/message/{messageID}</c>.
    /// </remarks>
    public virtual Task<SessionMessageResponse> GetMessageAsync(string messageId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(messageId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetMessage(SessionId, messageId), SessionMessageResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get permission request. Retrieve a pending permission request owned by a session.
    /// </summary>
    /// <param name = "requestId">The &apos;requestID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionPermissionResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.permission.get</c>: <c>GET /api/session/{sessionID}/permission/{requestID}</c>.
    /// </remarks>
    public virtual Task<SessionPermissionResponse> GetPermissionAsync(string requestId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(requestId);
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetPermission(SessionId, requestId), SessionPermissionResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Interrupt session execution. Interrupt active execution owned by this OpenCode process. Returns interrupted=true when an active execution was interrupted and false for the idle no-op. When resume=true, execution resumes pending steering input and next-in-line control items (manual compaction, moves) while queued prompts remain parked.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionInterruptResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.interrupt</c>: <c>POST /api/session/{sessionID}/interrupt</c>.
    /// </remarks>
    public virtual Task<SessionInterruptResponse> InterruptAsync(SessionInterruptRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.Interrupt(SessionId, request), SessionInterruptResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List session forms. Retrieve pending forms for a session.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionFormListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.form.list</c>: <c>GET /api/session/{sessionID}/form</c>.
    /// </remarks>
    public virtual Task<SessionFormListResponse> ListFormsAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.ListForms(SessionId), SessionFormListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List session inbox. List durable enqueued session work not yet delivered, ordered by enqueue sequence. Includes user, synthetic, compaction, and move items.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionInboxListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.inbox.list</c>: <c>GET /api/session/{sessionID}/inbox</c>.
    /// </remarks>
    public virtual Task<SessionInboxListResponse> ListInboxAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.ListInbox(SessionId), SessionInboxListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Get session messages. Retrieve projected messages for a session, optionally filtered by type. Items keep the requested order across pages; use cursor.next or cursor.previous to move through the ordered timeline, passing the same type filter on each page.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionMessageListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.message.list</c>: <c>GET /api/session/{sessionID}/message</c>.
    /// </remarks>
    public virtual Task<SessionMessageListResponse> ListMessagesAsync(SessionMessageListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.ListMessages(SessionId, request), SessionMessageListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Enumerates the items returned by &apos;GET /api/session/{sessionID}/message&apos; by following each opaque next cursor; every filter of the first request rides each continuation.
    /// </summary>
    /// <param name = "request">The request shaping the first page.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;ISessionMessageInfo&apos; sequence, whose Pages expose each &apos;SessionMessageListResponse&apos;.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned a declared error status (declared: 400, 401, 404, 500); pagination API errors always throw.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.message.list</c>: <c>GET /api/session/{sessionID}/message</c>.
    /// </remarks>
    public virtual CursorSequence<SessionMessageListResponse, ISessionMessageInfo> EnumerateMessagesAsync(SessionMessageListRequest? request = null, CancellationToken cancellationToken = default)
    {
        return CursorPaginator.EnumerateAsync(ListMessagesAsync, request, SessionMessageListResponseAdapter.Instance, cancellationToken);
    }

    /// <summary>
    /// List session permission requests. Retrieve pending permission requests owned by a session.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionPermissionListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.permission.list</c>: <c>GET /api/session/{sessionID}/permission</c>.
    /// </remarks>
    public virtual Task<SessionPermissionListResponse> ListRequestsAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.ListRequests(SessionId), SessionPermissionListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// View session. Mark the idle transition observed by the viewer as viewed.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionViewResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.view</c>: <c>POST /api/session/{sessionID}/view</c>.
    /// </remarks>
    public virtual Task<SessionViewResponse> MarkViewedAsync(SessionViewRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.MarkViewed(SessionId), request, OpenCodeJsonContext.Default.SessionViewRequest, SessionViewResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Move session. Move a session to another project directory at the requested delivery boundary.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionMoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.move</c>: <c>POST /api/session/{sessionID}/move</c>.
    /// </remarks>
    public virtual Task<SessionMoveResponse> MoveAsync(SessionMoveRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.Move(SessionId), request, OpenCodeJsonContext.Default.SessionMoveRequest, SessionMoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Background blocking session tools. Move active foreground backgroundable tools for this session into background observation. Idle requests are a no-op.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionBackgroundResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.background</c>: <c>POST /api/session/{sessionID}/background</c>.
    /// </remarks>
    public virtual Task<SessionBackgroundResponse> MoveToolsToBackgroundAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.MoveToolsToBackground(SessionId), SessionBackgroundResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Send message. Durably admit one session input and schedule agent-loop execution unless resume is false.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionPromptResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.prompt</c>: <c>POST /api/session/{sessionID}/prompt</c>.
    /// </remarks>
    public virtual Task<SessionPromptResponse> PromptAsync(SessionPromptRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.Prompt(SessionId), request, OpenCodeJsonContext.Default.SessionPromptRequest, SessionPromptResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Delete session. Delete a session and its child sessions.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.remove</c>: <c>DELETE /api/session/{sessionID}</c>.
    /// </remarks>
    public virtual Task<SessionRemoveResponse> RemoveAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Sessions.Remove(SessionId), SessionRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Reply to form. Submit an answer to a pending form.
    /// </summary>
    /// <param name = "formId">The &apos;formID&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionFormReplyResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.form.reply</c>: <c>POST /api/session/{sessionID}/form/{formID}/reply</c>.
    /// </remarks>
    public virtual Task<SessionFormReplyResponse> ReplyToFormAsync(string formId, SessionFormReplyRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(formId);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.ReplyToForm(SessionId, formId), request, OpenCodeJsonContext.Default.SessionFormReplyRequest, SessionFormReplyResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Reply to pending permission request. Respond to a pending permission request owned by a session.
    /// </summary>
    /// <param name = "requestId">The &apos;requestID&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionPermissionReplyResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.permission.reply</c>: <c>POST /api/session/{sessionID}/permission/{requestID}/reply</c>.
    /// </remarks>
    public virtual Task<SessionPermissionReplyResponse> ReplyToPermissionAsync(string requestId, SessionPermissionReplyRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(requestId);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.ReplyToPermission(SessionId, requestId), request, OpenCodeJsonContext.Default.SessionPermissionReplyRequest, SessionPermissionReplyResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Run command. Execute a slash command callback immediately.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionCommandResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.command</c>: <c>POST /api/session/{sessionID}/command</c>.
    /// </remarks>
    public virtual Task<SessionCommandResponse> RunCommandAsync(SessionCommandRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.RunCommand(SessionId), request, OpenCodeJsonContext.Default.SessionCommandRequest, SessionCommandResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Run shell command. Execute one shell command in the session&apos;s working directory. Emits a shell.started event before execution and a shell.ended event with the merged output after.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionShellResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.shell</c>: <c>POST /api/session/{sessionID}/shell</c>.
    /// </remarks>
    public virtual Task<SessionShellResponse> RunShellCommandAsync(SessionShellRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.RunShellCommand(SessionId), request, OpenCodeJsonContext.Default.SessionShellRequest, SessionShellResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Set session environment. Replace the process environment used by local shell commands for this session.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionEnvironmentResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.environment</c>: <c>PUT /api/session/{sessionID}/environment</c>.
    /// </remarks>
    public virtual Task<SessionEnvironmentResponse> SetEnvironmentAsync(SessionEnvironmentRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Put, OpenCodeRoutes.Sessions.SetEnvironment(SessionId), request, OpenCodeJsonContext.Default.SessionEnvironmentRequest, SessionEnvironmentResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Stage session revert. Stage or move a reversible session boundary and optionally apply its file changes.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionRevertStageResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409, 500) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.revert.stage</c>: <c>POST /api/session/{sessionID}/revert/stage</c>.
    /// </remarks>
    public virtual Task<SessionRevertStageResponse> StageRevertAsync(SessionRevertStageRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.StageRevert(SessionId), request, OpenCodeJsonContext.Default.SessionRevertStageRequest, SessionRevertStageResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Switch session agent. Switch the agent used by subsequent provider turns.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionSwitchAgentResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.switchAgent</c>: <c>POST /api/session/{sessionID}/agent</c>.
    /// </remarks>
    public virtual Task<SessionSwitchAgentResponse> SwitchAgentAsync(SessionSwitchAgentRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.SwitchAgent(SessionId), request, OpenCodeJsonContext.Default.SessionSwitchAgentRequest, SessionSwitchAgentResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Switch session model. Switch the model used by subsequent provider turns.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionSwitchModelResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.switchModel</c>: <c>POST /api/session/{sessionID}/model</c>.
    /// </remarks>
    public virtual Task<SessionSwitchModelResponse> SwitchModelAsync(SessionSwitchModelRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.SwitchModel(SessionId), request, OpenCodeJsonContext.Default.SessionSwitchModelRequest, SessionSwitchModelResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Update session. Update mutable session properties.
    /// </summary>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionUpdateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.update</c>: <c>PATCH /api/session/{sessionID}</c>.
    /// </remarks>
    public virtual Task<SessionUpdateResponse> UpdateAsync(SessionUpdateRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(OpenCodeHttpMethod.Patch, OpenCodeRoutes.Sessions.Update(SessionId), request ?? EmptySessionUpdateRequest, OpenCodeJsonContext.Default.SessionUpdateRequest, SessionUpdateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Update inbox item. Change a pending inbox item&apos;s delivery mode. Steering wakes session execution.
    /// </summary>
    /// <param name = "inboxId">The &apos;inboxID&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionInboxUpdateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.inbox.update</c>: <c>PATCH /api/session/{sessionID}/inbox/{inboxID}</c>.
    /// </remarks>
    public virtual Task<SessionInboxUpdateResponse> UpdateInboxAsync(string inboxId, SessionInboxUpdateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(inboxId);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(OpenCodeHttpMethod.Patch, OpenCodeRoutes.Sessions.UpdateInbox(SessionId, inboxId), request, OpenCodeJsonContext.Default.SessionInboxUpdateRequest, SessionInboxUpdateResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
