// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.Pagination;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;SessionsClient&apos; collection client.
/// </summary>
public class SessionsClient
{
    private static readonly SessionCreateRequest EmptySessionCreateRequest = new();
    private readonly Pipeline? _pipeline;
    internal SessionsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected SessionsClient()
    {
    }

    /// <summary>
    /// Gets a bound &apos;SessionClient&apos;; the handle never caches server state.
    /// </summary>
    /// <param name = "sessionId">The &apos;sessionID&apos; route value.</param>
    /// <returns>The bound &apos;SessionClient&apos;.</returns>
    public virtual SessionClient GetSessionClient(string sessionId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sessionId);
        if (sessionId is "." or "..")
        {
            throw new ArgumentException("Route values must not be dot segments.", nameof(sessionId));
        }

        return new SessionClient(Pipeline, sessionId);
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("SessionsClient", "Pipeline");

    /// <summary>
    /// Create session. Create a session at the requested location. A parentID creates a linked child session at its parent&apos;s location.
    /// </summary>
    /// <param name = "request">The request body; an empty body is sent when omitted.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionCreateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.create</c>: <c>POST /api/session</c>.
    /// </remarks>
    public virtual Task<SessionCreateResponse> CreateSessionAsync(SessionCreateRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Sessions.CreateSession, request ?? EmptySessionCreateRequest, OpenCodeJsonContext.Default.SessionCreateRequest, SessionCreateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List active sessions. Retrieve foreground Session drains currently owned by this OpenCode process. Sessions absent from the result are inactive.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionActiveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.active</c>: <c>GET /api/session/active</c>.
    /// </remarks>
    public virtual Task<SessionActiveResponse> GetActiveAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.GetActive, SessionActiveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List sessions. Retrieve sessions in the requested order. Items keep that order across pages; use cursor.next or cursor.previous to move through the ordered list.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.list</c>: <c>GET /api/session</c>.
    /// </remarks>
    public virtual Task<SessionListResponse> ListSessionsAsync(SessionListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Sessions.ListSessions(request), SessionListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Enumerates the items returned by &apos;GET /api/session&apos; by following each opaque next cursor; every filter of the first request rides each continuation.
    /// </summary>
    /// <param name = "request">The request shaping the first page.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;SessionInfo&apos; sequence, whose Pages expose each &apos;SessionListResponse&apos;.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned a declared error status (declared: 400, 401); pagination API errors always throw.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>session.list</c>: <c>GET /api/session</c>.
    /// </remarks>
    public virtual CursorSequence<SessionListResponse, SessionInfo> EnumerateSessionsAsync(SessionListRequest? request = null, CancellationToken cancellationToken = default)
    {
        return CursorPaginator.EnumerateAsync(ListSessionsAsync, request, SessionListResponseAdapter.Instance, cancellationToken);
    }
}
