// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The opencode API client and composition root.
/// </summary>
public class OpenCodeClient : IDisposable
{
    private readonly Pipeline? _pipeline;
    private readonly AgentsClient? _agents;
    private readonly CommandsClient? _commands;
    private readonly ConfigClient? _config;
    private readonly CredentialsClient? _credentials;
    private readonly DebugClient? _debug;
    private readonly EventsClient? _events;
    private readonly ExperimentalClient? _experimental;
    private readonly FileSystemClient? _fileSystem;
    private readonly FormsClient? _forms;
    private readonly IntegrationsClient? _integrations;
    private readonly LanguageModelsClient? _languageModels;
    private readonly McpServersClient? _mcpServers;
    private readonly PermissionsClient? _permissions;
    private readonly PersistentPtysClient? _persistentPtys;
    private readonly PluginsClient? _plugins;
    private readonly ProjectsClient? _projects;
    private readonly ProvidersClient? _providers;
    private readonly PtysClient? _ptys;
    private readonly ReferencesClient? _references;
    private readonly RpcClient? _rpc;
    private readonly ServerClient? _server;
    private readonly SessionsClient? _sessions;
    private readonly ShellsClient? _shells;
    private readonly SkillsClient? _skills;
    private readonly VcsClient? _vcs;
    private readonly WebsearchClient? _websearch;
    private readonly WorktreesClient? _worktrees;
    /// <summary>
    /// Initializes a client that owns its connection to the endpoint.
    /// </summary>
    /// <param name = "options">The client options; the endpoint is required.</param>
    public OpenCodeClient(OpenCodeClientOptions options)
    {
        _pipeline = Pipeline.Create(options);
        _agents = new AgentsClient(_pipeline);
        _commands = new CommandsClient(_pipeline);
        _config = new ConfigClient(_pipeline);
        _credentials = new CredentialsClient(_pipeline);
        _debug = new DebugClient(_pipeline);
        _events = new EventsClient(_pipeline);
        _experimental = new ExperimentalClient(_pipeline);
        _fileSystem = new FileSystemClient(_pipeline);
        _forms = new FormsClient(_pipeline);
        _integrations = new IntegrationsClient(_pipeline);
        _languageModels = new LanguageModelsClient(_pipeline);
        _mcpServers = new McpServersClient(_pipeline);
        _permissions = new PermissionsClient(_pipeline);
        _persistentPtys = new PersistentPtysClient(_pipeline);
        _plugins = new PluginsClient(_pipeline);
        _projects = new ProjectsClient(_pipeline);
        _providers = new ProvidersClient(_pipeline);
        _ptys = new PtysClient(_pipeline);
        _references = new ReferencesClient(_pipeline);
        _rpc = new RpcClient(_pipeline);
        _server = new ServerClient(_pipeline);
        _sessions = new SessionsClient(_pipeline);
        _shells = new ShellsClient(_pipeline);
        _skills = new SkillsClient(_pipeline);
        _vcs = new VcsClient(_pipeline);
        _websearch = new WebsearchClient(_pipeline);
        _worktrees = new WorktreesClient(_pipeline);
    }

    /// <summary>
    /// Initializes a client over an injected transport the client never disposes; friend-assembly test surface.
    /// </summary>
    /// <param name = "httpClient">The injected HTTP client.</param>
    /// <param name = "options">The client options; the endpoint is required.</param>
    internal OpenCodeClient(HttpClient httpClient, OpenCodeClientOptions options)
    {
        _pipeline = Pipeline.Create(httpClient, options);
        _agents = new AgentsClient(_pipeline);
        _commands = new CommandsClient(_pipeline);
        _config = new ConfigClient(_pipeline);
        _credentials = new CredentialsClient(_pipeline);
        _debug = new DebugClient(_pipeline);
        _events = new EventsClient(_pipeline);
        _experimental = new ExperimentalClient(_pipeline);
        _fileSystem = new FileSystemClient(_pipeline);
        _forms = new FormsClient(_pipeline);
        _integrations = new IntegrationsClient(_pipeline);
        _languageModels = new LanguageModelsClient(_pipeline);
        _mcpServers = new McpServersClient(_pipeline);
        _permissions = new PermissionsClient(_pipeline);
        _persistentPtys = new PersistentPtysClient(_pipeline);
        _plugins = new PluginsClient(_pipeline);
        _projects = new ProjectsClient(_pipeline);
        _providers = new ProvidersClient(_pipeline);
        _ptys = new PtysClient(_pipeline);
        _references = new ReferencesClient(_pipeline);
        _rpc = new RpcClient(_pipeline);
        _server = new ServerClient(_pipeline);
        _sessions = new SessionsClient(_pipeline);
        _shells = new ShellsClient(_pipeline);
        _skills = new SkillsClient(_pipeline);
        _vcs = new VcsClient(_pipeline);
        _websearch = new WebsearchClient(_pipeline);
        _worktrees = new WorktreesClient(_pipeline);
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected OpenCodeClient()
    {
    }

    /// <summary>
    /// Releases the owned transport resources.
    /// </summary>
    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Releases the owned transport resources.
    /// </summary>
    /// <param name = "disposing">Whether managed state should be released.</param>
    protected virtual void Dispose(bool disposing)
    {
        if (disposing)
        {
            _pipeline?.Dispose();
        }
    }

    /// <summary>
    /// Gets the &apos;Agents&apos; collection client.
    /// </summary>
    public virtual AgentsClient Agents => _agents ?? throw MockSeam.CreateError("OpenCodeClient", "Agents");
    /// <summary>
    /// Gets the &apos;Commands&apos; collection client.
    /// </summary>
    public virtual CommandsClient Commands => _commands ?? throw MockSeam.CreateError("OpenCodeClient", "Commands");
    /// <summary>
    /// Gets the &apos;Config&apos; collection client.
    /// </summary>
    public virtual ConfigClient Config => _config ?? throw MockSeam.CreateError("OpenCodeClient", "Config");
    /// <summary>
    /// Gets the &apos;Credentials&apos; collection client.
    /// </summary>
    public virtual CredentialsClient Credentials => _credentials ?? throw MockSeam.CreateError("OpenCodeClient", "Credentials");
    /// <summary>
    /// Gets the &apos;Debug&apos; collection client.
    /// </summary>
    public virtual DebugClient Debug => _debug ?? throw MockSeam.CreateError("OpenCodeClient", "Debug");
    /// <summary>
    /// Gets the &apos;Events&apos; collection client.
    /// </summary>
    public virtual EventsClient Events => _events ?? throw MockSeam.CreateError("OpenCodeClient", "Events");
    /// <summary>
    /// Gets the &apos;Experimental&apos; collection client.
    /// </summary>
    public virtual ExperimentalClient Experimental => _experimental ?? throw MockSeam.CreateError("OpenCodeClient", "Experimental");
    /// <summary>
    /// Gets the &apos;FileSystem&apos; collection client.
    /// </summary>
    public virtual FileSystemClient FileSystem => _fileSystem ?? throw MockSeam.CreateError("OpenCodeClient", "FileSystem");
    /// <summary>
    /// Gets the &apos;Forms&apos; collection client.
    /// </summary>
    public virtual FormsClient Forms => _forms ?? throw MockSeam.CreateError("OpenCodeClient", "Forms");
    /// <summary>
    /// Gets the &apos;Integrations&apos; collection client.
    /// </summary>
    public virtual IntegrationsClient Integrations => _integrations ?? throw MockSeam.CreateError("OpenCodeClient", "Integrations");
    /// <summary>
    /// Gets the &apos;LanguageModels&apos; collection client.
    /// </summary>
    public virtual LanguageModelsClient LanguageModels => _languageModels ?? throw MockSeam.CreateError("OpenCodeClient", "LanguageModels");
    /// <summary>
    /// Gets the &apos;McpServers&apos; collection client.
    /// </summary>
    public virtual McpServersClient McpServers => _mcpServers ?? throw MockSeam.CreateError("OpenCodeClient", "McpServers");
    /// <summary>
    /// Gets the &apos;Permissions&apos; collection client.
    /// </summary>
    public virtual PermissionsClient Permissions => _permissions ?? throw MockSeam.CreateError("OpenCodeClient", "Permissions");
    /// <summary>
    /// Gets the &apos;PersistentPtys&apos; collection client.
    /// </summary>
    public virtual PersistentPtysClient PersistentPtys => _persistentPtys ?? throw MockSeam.CreateError("OpenCodeClient", "PersistentPtys");
    /// <summary>
    /// Gets the &apos;Plugins&apos; collection client.
    /// </summary>
    public virtual PluginsClient Plugins => _plugins ?? throw MockSeam.CreateError("OpenCodeClient", "Plugins");
    /// <summary>
    /// Gets the &apos;Projects&apos; collection client.
    /// </summary>
    public virtual ProjectsClient Projects => _projects ?? throw MockSeam.CreateError("OpenCodeClient", "Projects");
    /// <summary>
    /// Gets the &apos;Providers&apos; collection client.
    /// </summary>
    public virtual ProvidersClient Providers => _providers ?? throw MockSeam.CreateError("OpenCodeClient", "Providers");
    /// <summary>
    /// Gets the &apos;Ptys&apos; collection client.
    /// </summary>
    public virtual PtysClient Ptys => _ptys ?? throw MockSeam.CreateError("OpenCodeClient", "Ptys");
    /// <summary>
    /// Gets the &apos;References&apos; collection client.
    /// </summary>
    public virtual ReferencesClient References => _references ?? throw MockSeam.CreateError("OpenCodeClient", "References");
    /// <summary>
    /// Gets the &apos;Rpc&apos; collection client.
    /// </summary>
    public virtual RpcClient Rpc => _rpc ?? throw MockSeam.CreateError("OpenCodeClient", "Rpc");
    /// <summary>
    /// Gets the &apos;Server&apos; collection client.
    /// </summary>
    public virtual ServerClient Server => _server ?? throw MockSeam.CreateError("OpenCodeClient", "Server");
    /// <summary>
    /// Gets the &apos;Sessions&apos; collection client.
    /// </summary>
    public virtual SessionsClient Sessions => _sessions ?? throw MockSeam.CreateError("OpenCodeClient", "Sessions");
    /// <summary>
    /// Gets the &apos;Shells&apos; collection client.
    /// </summary>
    public virtual ShellsClient Shells => _shells ?? throw MockSeam.CreateError("OpenCodeClient", "Shells");
    /// <summary>
    /// Gets the &apos;Skills&apos; collection client.
    /// </summary>
    public virtual SkillsClient Skills => _skills ?? throw MockSeam.CreateError("OpenCodeClient", "Skills");
    /// <summary>
    /// Gets the &apos;Vcs&apos; collection client.
    /// </summary>
    public virtual VcsClient Vcs => _vcs ?? throw MockSeam.CreateError("OpenCodeClient", "Vcs");
    /// <summary>
    /// Gets the &apos;Websearch&apos; collection client.
    /// </summary>
    public virtual WebsearchClient Websearch => _websearch ?? throw MockSeam.CreateError("OpenCodeClient", "Websearch");
    /// <summary>
    /// Gets the &apos;Worktrees&apos; collection client.
    /// </summary>
    public virtual WorktreesClient Worktrees => _worktrees ?? throw MockSeam.CreateError("OpenCodeClient", "Worktrees");
    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("OpenCodeClient", "Pipeline");

    /// <summary>
    /// Get location. Resolve the requested location or the server default location.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;LocationResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>location.get</c>: <c>GET /api/location</c>.
    /// </remarks>
    public virtual Task<LocationResponse> GetLocationAsync(LocationRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Location.Get(request), LocationResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Reload configuration. Shut down and rebuild every loaded location. Pending permissions and forms are cancelled; running sessions continue with fresh services at the next step boundary. Emits location.shutdown for client recovery and responds once all replacement builds settle.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;LocationReloadResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 503) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>location.reload</c>: <c>POST /api/location/reload</c>.
    /// </remarks>
    public virtual Task<LocationReloadResponse> ReloadLocationsAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Location.ReloadLocations, LocationReloadResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
