// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;POST /api/credential&apos; operation.
/// </summary>
public sealed record CredentialCreateResponse : OpenCodeResponse
{
    private readonly CredentialEntry? _credential;
    /// <summary>
    /// Initializes a success instance of the &apos;CredentialCreateResponse&apos; envelope.
    /// </summary>
    public CredentialCreateResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal CredentialCreateResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Credential = null!;
    }

    /// <summary>
    /// Gets the Credential payload; guarded on the error path.
    /// </summary>
    public required CredentialEntry Credential { get => _credential ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Credential."); init => _credential = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_credential is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Credential = ").Append(_credential);
        return true;
    }
}
