// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;
using OpenCode.Sdk.Internal.Serialization;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;CredentialsClient&apos; collection client.
/// </summary>
public class CredentialsClient
{
    private readonly Pipeline? _pipeline;
    internal CredentialsClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected CredentialsClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("CredentialsClient", "Pipeline");

    /// <summary>
    /// Activate credential. Activate a stored integration credential.
    /// </summary>
    /// <param name = "credentialId">The &apos;credentialID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;CredentialActivateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>credential.activate</c>: <c>POST /api/credential/{credentialID}/activate</c>.
    /// </remarks>
    public virtual Task<CredentialActivateResponse> ActivateCredentialAsync(string credentialId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(credentialId);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Credentials.ActivateCredential(credentialId), CredentialActivateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Create credential. Store an integration credential. It becomes the integration&apos;s active credential unless activate is false and the integration already has one. Fails with a conflict when the requested ID already exists.
    /// </summary>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;CredentialCreateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 409) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>credential.create</c>: <c>POST /api/credential</c>.
    /// </remarks>
    public virtual Task<CredentialCreateResponse> CreateCredentialAsync(CredentialCreateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(HttpMethod.Post, OpenCodeRoutes.Credentials.CreateCredential, request, OpenCodeJsonContext.Default.CredentialCreateRequest, CredentialCreateResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List credentials. List every stored integration credential, including its secret value.
    /// </summary>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;CredentialListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>credential.list</c>: <c>GET /api/credential</c>.
    /// </remarks>
    public virtual Task<CredentialListResponse> ListCredentialsAsync(OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.Credentials.ListCredentials, CredentialListResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Remove credential. Remove a stored integration credential.
    /// </summary>
    /// <param name = "credentialId">The &apos;credentialID&apos; route value.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;CredentialRemoveResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>credential.remove</c>: <c>DELETE /api/credential/{credentialID}</c>.
    /// </remarks>
    public virtual Task<CredentialRemoveResponse> RemoveCredentialAsync(string credentialId, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(credentialId);
        return Pipeline.ExecuteAsync(HttpMethod.Delete, OpenCodeRoutes.Credentials.RemoveCredential(credentialId), CredentialRemoveResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// Update credential. Update a stored credential label.
    /// </summary>
    /// <param name = "credentialId">The &apos;credentialID&apos; route value.</param>
    /// <param name = "request">The request body.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;CredentialUpdateResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>credential.update</c>: <c>PATCH /api/credential/{credentialID}</c>.
    /// </remarks>
    public virtual Task<CredentialUpdateResponse> UpdateCredentialAsync(string credentialId, CredentialUpdateRequest request, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrEmpty(credentialId);
        ArgumentNullException.ThrowIfNull(request);
        return Pipeline.ExecuteAsync(OpenCodeHttpMethod.Patch, OpenCodeRoutes.Credentials.UpdateCredential(credentialId), request, OpenCodeJsonContext.Default.CredentialUpdateRequest, CredentialUpdateResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
