// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using System.Diagnostics.CodeAnalysis;
using System.Text;
using OpenCode.Sdk.Models;

namespace OpenCode.Sdk;
/// <summary>
/// Represents the response of the &apos;GET /api/credential&apos; operation.
/// </summary>
public sealed record CredentialListResponse : OpenCodeResponse
{
    private readonly IReadOnlyList<CredentialEntry>? _credentials;
    /// <summary>
    /// Initializes a success instance of the &apos;CredentialListResponse&apos; envelope.
    /// </summary>
    public CredentialListResponse()
    {
    }

    /// <summary>
    /// Initializes an error-path instance; the payload stays unset behind its guard.
    /// </summary>
    [SetsRequiredMembers]
    internal CredentialListResponse(int status, IOpenCodeError? error, string? rawBody)
    {
        Status = status;
        IsError = true;
        Error = error;
        RawBody = rawBody;
        Credentials = null!;
    }

    /// <summary>
    /// Gets the Credentials payload; guarded on the error path.
    /// </summary>
    public required IReadOnlyList<CredentialEntry> Credentials { get => _credentials ?? throw new InvalidOperationException("The response is an error; check IsError before accessing Credentials."); init => _credentials = value; }

    /// <summary>
    /// Prints the shared metadata and appends the payload only when it is present.
    /// </summary>
    protected override bool PrintMembers(StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var printed = base.PrintMembers(builder);
        if (_credentials is null)
        {
            return printed;
        }

        if (printed)
        {
            _ = builder.Append(", ");
        }

        _ = builder.Append("Credentials = ").Append(_credentials);
        return true;
    }
}
