// Generated by OpenCode.Sdk.Tools from spec/openapi.json.
// Do not edit by hand — change tools/curation.json or the emitters, then regenerate.
using OpenCode.Sdk.Internal;
using OpenCode.Sdk.Internal.ResponseAdapters;

namespace OpenCode.Sdk;
/// <summary>
/// The &apos;McpServersClient&apos; collection client.
/// </summary>
public class McpServersClient
{
    private readonly Pipeline? _pipeline;
    internal McpServersClient(Pipeline pipeline)
    {
        ArgumentNullException.ThrowIfNull(pipeline);
        _pipeline = pipeline;
    }

    /// <summary>
    /// Initializes a mocking instance; members invoked without an override throw an instructive failure.
    /// </summary>
    protected McpServersClient()
    {
    }

    private Pipeline Pipeline => _pipeline ?? throw MockSeam.CreateError("McpServersClient", "Pipeline");

    /// <summary>
    /// List MCP resources. Retrieve resources and resource templates from connected MCP servers.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;McpResourceCatalogResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>mcp.resource.catalog</c>: <c>GET /api/mcp/resource</c>.
    /// </remarks>
    public virtual Task<McpResourceCatalogResponse> GetResourceCatalogAsync(McpResourceCatalogRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.McpServers.GetResourceCatalog(request), McpResourceCatalogResponseAdapter.Instance, requestOptions, cancellationToken);
    }

    /// <summary>
    /// List MCP servers. Retrieve configured MCP servers and their connection status.
    /// </summary>
    /// <param name = "request">The request shaping the query.</param>
    /// <param name = "requestOptions">The per-call options.</param>
    /// <param name = "cancellationToken">The cancellation token.</param>
    /// <returns>The &apos;McpListResponse&apos; envelope.</returns>
    /// <exception cref = "OpenCodeApiException">The API returned an error status (declared: 400, 401, 404) and NoThrow was not selected.</exception>
    /// <exception cref = "OpenCodeTransportException">The server could not be reached or returned a malformed success body.</exception>
    /// <remarks>
    /// Operation <c>mcp.list</c>: <c>GET /api/mcp</c>.
    /// </remarks>
    public virtual Task<McpListResponse> ListMcpServersAsync(McpListRequest? request = null, OpenCodeRequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        return Pipeline.ExecuteAsync(HttpMethod.Get, OpenCodeRoutes.McpServers.ListMcpServers(request), McpListResponseAdapter.Instance, requestOptions, cancellationToken);
    }
}
